TARGET_CFLAGS   = -DPOSIX -m32 -D_POSIX_SOURCE -D_GNU_SOURCE 
TARGET_LDFLAGS  =  -lpthread -lrt -m32
SIMULINK_LDFLAGS  = -lm
CC              = gcc
LD              = ld
GPROF           = gprof


ifdef USE_GPROF
TARGET_LDFLAGS+=-pg
endif



target-clean:

target-objects:
