TARGET_CFLAGS   = -DPOSIX -D_POSIX_SOURCE -D_GNU_SOURCE $(GCC_GENERIC_FLAGS) -D__PO_HI_USE_VCD
TARGET_LDFLAGS  =  -lpthread -lrt -L$(RUNTIME_PATH)/libs/linux32/  -L$(RUNTIME_PATH)/libs/linux64/ -llua -lm
SIMULINK_LDFLAGS  = -lm
CC              = gcc
LD              = gcc
GPROF           = gprof


ifdef USE_GPROF
TARGET_LDFLAGS+=-pg
endif



target-clean:

target-objects:
