TARGET_CFLAGS   = -DPOSIX -D_POSIX_SOURCE -D_GNU_SOURCE -DCOMPCERT  -flonglong -DHAVE_STDINT_H=1
TARGET_LDFLAGS  =  -lpthread -lrt
SIMULINK_LDFLAGS  = -lm
CC              = ccomp
LD              = ccomp
GPROF           = gprof


ifdef USE_GPROF
TARGET_LDFLAGS+=-pg
endif

target-clean:

target-objects:
