TARGET_CFLAGS     = -D_WIN32 -D_GNU_SOURCE  $(GCC_GENERIC_FLAGS) -std=c99 -m32
TARGET_LDFLAGS    =  -m32
SIMULINK_LDFLAGS  = -lm
CC                = i686-w64-mingw32-gcc
LD                = i686-w64-mingw32-ld
GPROF             = gprof

ifdef USE_GPROF
TARGET_LDFLAGS+=-pg
endif

target-clean:

target-objects:
