TARGET_CFLAGS     = -DPOSIX -m32 -D_POSIX_SOURCE -D_GNU_SOURCE  $(GCC_GENERIC_FLAGS)
TARGET_LDFLAGS    =  -lpthread -lrt -m32
SIMULINK_LDFLAGS  = -lm
CC                = gcc
LD                = ld
GPROF             = gprof

USE_USB_BRICK=$(shell grep __PO_HI_NEED_DRIVER_SPACEWIRE_USB_BRICK deployment.h|wc -l)

ifdef USE_GPROF
TARGET_LDFLAGS+=-pg
endif

ifeq ($(USE_USB_BRICK),1)
TARGET_LDFLAGS+=-lSpaceWireUSBAPI -lConfigLibraryUSB
endif

target-clean:

target-objects:
