#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE mgmt_k

#define __po_hi_sensor_sim_nb_ports 3

#define __po_hi_stall_monitor_nb_ports 3

#define __po_hi_hci_nb_ports 5

#define __po_hi_landing_gear_nb_ports 4

#define __po_hi_operator_nb_ports 1

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  mgmt_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  mgmt_sensor_sim_k_entity = 0,
  mgmt_stall_monitor_k_entity = 1,
  mgmt_hci_k_entity = 2,
  mgmt_landing_gear_k_entity = 3,
  mgmt_operator_k_entity = 4,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  mgmt_sensor_sim_k = 0,
  mgmt_stall_monitor_k = 1,
  mgmt_hci_k = 2,
  mgmt_landing_gear_k = 3,
  mgmt_operator_k = 4,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 5

#define __PO_HI_NB_PROTECTED 0

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 5

#define __PO_HI_NB_PORTS 16

typedef enum
{
  sensor_sim_global_aoa = 0,
  sensor_sim_global_climb_rate = 1,
  sensor_sim_global_engine_failure = 2,
  stall_monitor_global_aoa = 3,
  stall_monitor_global_climb_rate = 4,
  stall_monitor_global_stall_warn = 5,
  hci_global_stall_warning = 6,
  hci_global_engine_failure = 7,
  hci_global_gear_cmd = 8,
  hci_global_gear_req = 9,
  hci_global_gear_ack = 10,
  landing_gear_global_req = 11,
  landing_gear_global_ack = 12,
  landing_gear_global_dummy_out = 13,
  landing_gear_global_dummy_in = 14,
  operator_global_gear_cmd = 15,
  invalid_port_t = -1,
  constant_out_identifier = 17
} __po_hi_port_t;

typedef enum
{
  sensor_sim_local_aoa = 0,
  sensor_sim_local_climb_rate = 1,
  sensor_sim_local_engine_failure = 2,
  stall_monitor_local_aoa = 0,
  stall_monitor_local_climb_rate = 1,
  stall_monitor_local_stall_warn = 2,
  hci_local_stall_warning = 0,
  hci_local_engine_failure = 1,
  hci_local_gear_cmd = 2,
  hci_local_gear_req = 3,
  hci_local_gear_ack = 4,
  landing_gear_local_req = 0,
  landing_gear_local_ack = 1,
  landing_gear_local_dummy_out = 2,
  landing_gear_local_dummy_in = 3,
  operator_local_gear_cmd = 0,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 0

#define __PO_HI_NB_PROTOCOLS 0

#endif
