#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <po_hi_types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      software__ravenscar_integer sensor_sim_global_aoa;

    } sensor_sim_global_aoa;

    struct
    {
      software__ravenscar_integer sensor_sim_global_climb_rate;

    } sensor_sim_global_climb_rate;

    struct
    {
      __po_hi_bool_t sensor_sim_global_engine_failure;

    } sensor_sim_global_engine_failure;

    struct
    {
      software__ravenscar_integer stall_monitor_global_aoa;

    } stall_monitor_global_aoa;

    struct
    {
      software__ravenscar_integer stall_monitor_global_climb_rate;

    } stall_monitor_global_climb_rate;

    struct
    {
      software__ravenscar_integer stall_monitor_global_stall_warn;

    } stall_monitor_global_stall_warn;

    struct
    {
      software__ravenscar_integer hci_global_stall_warning;

    } hci_global_stall_warning;

    struct
    {
      __po_hi_bool_t hci_global_engine_failure;

    } hci_global_engine_failure;

    struct
    {
      __po_hi_bool_t hci_global_gear_cmd;

    } hci_global_gear_cmd;

    struct
    {
      __po_hi_bool_t hci_global_gear_req;

    } hci_global_gear_req;

    struct
    {
      __po_hi_bool_t hci_global_gear_ack;

    } hci_global_gear_ack;

    struct
    {
      __po_hi_bool_t landing_gear_global_req;

    } landing_gear_global_req;

    struct
    {
      __po_hi_bool_t landing_gear_global_ack;

    } landing_gear_global_ack;

    struct
    {
      __po_hi_bool_t landing_gear_global_dummy_out;

    } landing_gear_global_dummy_out;

    struct
    {
      __po_hi_bool_t landing_gear_global_dummy_in;

    } landing_gear_global_dummy_in;

    struct
    {
      __po_hi_bool_t operator_global_gear_cmd;

    } operator_global_gear_cmd;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
