#include <deployment.h>
#include <po_hi_types.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_bus_id device_device_a_accessed_buses[1] = {bus_the_bus};
extern __po_hi_c_ip_conf_t* pohidrv_device_a;
__po_hi_bus_id device_device_b_accessed_buses[1] = {bus_the_bus};
extern __po_hi_c_ip_conf_t* pohidrv_device_b;
__po_hi_entity_t __po_hi_port_global_to_entity[__PO_HI_NB_PORTS] = {pr_a_producer_k_entity,pr_a_result_consumer_k_entity,pr_b_consumer_k_entity,pr_b_result_producer_k_entity};
char* __po_hi_port_global_names[__PO_HI_NB_PORTS] = {"producer_global_data_source","result_consumer_global_data_sink","consumer_global_data_sink","result_producer_global_data_source"};
char* __po_hi_port_global_model_names[__PO_HI_NB_PORTS] = {"data_source","data_sink","data_sink","data_source"};
__po_hi_port_kind_t __po_hi_port_global_kind[__PO_HI_NB_PORTS] = {__PO_HI_OUT_DATA_INTER_PROCESS,__PO_HI_IN_DATA_INTER_PROCESS,__PO_HI_IN_DATA_INTER_PROCESS,__PO_HI_OUT_DATA_INTER_PROCESS};
__po_hi_uint32_t __po_hi_port_global_data_size[__PO_HI_NB_PORTS] = {sizeof (int),sizeof (int),sizeof (int),sizeof (int)};
__po_hi_uint32_t __po_hi_port_global_queue_size[__PO_HI_NB_PORTS] = {1,1,1,1};
__po_hi_local_port_t __po_hi_port_global_to_local[__PO_HI_NB_PORTS] = {producer_local_data_source,result_consumer_local_data_sink,consumer_local_data_sink,result_producer_local_data_source};
__po_hi_node_t __po_hi_entity_table[__PO_HI_NB_ENTITIES] = {pr_a_k,pr_a_k,pr_b_k,pr_b_k};
__po_hi_uint8_t __po_hi_deployment_endiannesses[__PO_HI_NB_NODES] = {__PO_HI_LITTLEENDIAN,__PO_HI_LITTLEENDIAN};
char* __po_hi_devices_naming[__PO_HI_NB_DEVICES] = {"noaddr","noaddr"};
__po_hi_uint32_t* __po_hi_devices_configuration_values[__PO_HI_NB_DEVICES] = {(__po_hi_uint32_t*)&(pohidrv_device_a),(__po_hi_uint32_t*)&(pohidrv_device_b)};
__po_hi_uint32_t __po_hi_devices_nb_accessed_buses[__PO_HI_NB_DEVICES] = {1,1};
__po_hi_bus_id* __po_hi_devices_accessed_buses[__PO_HI_NB_DEVICES] = {device_device_a_accessed_buses,device_device_b_accessed_buses};
__po_hi_device_id __po_hi_port_to_device[__PO_HI_NB_PORTS] = {device_a_device_id,device_a_device_id,device_b_device_id,device_b_device_id};
__po_hi_port_t __po_hi_devices_to_nodes[__PO_HI_NB_DEVICES] = {pr_a_k,pr_b_k};

