pragma Ada_95;
pragma Warnings (Off);
pragma Source_File_Name (ada_main, Spec_File_Name => "b__ocarina_cmd.ads");
pragma Source_File_Name (ada_main, Body_File_Name => "b__ocarina_cmd.adb");
pragma Suppress (Overflow_Check);
with Ada.Exceptions;

package body ada_main is

   E077 : Short_Integer; pragma Import (Ada, E077, "system__os_lib_E");
   E011 : Short_Integer; pragma Import (Ada, E011, "system__soft_links_E");
   E021 : Short_Integer; pragma Import (Ada, E021, "system__exception_table_E");
   E164 : Short_Integer; pragma Import (Ada, E164, "ada__containers_E");
   E065 : Short_Integer; pragma Import (Ada, E065, "ada__io_exceptions_E");
   E369 : Short_Integer; pragma Import (Ada, E369, "ada__numerics_E");
   E092 : Short_Integer; pragma Import (Ada, E092, "ada__strings_E");
   E094 : Short_Integer; pragma Import (Ada, E094, "ada__strings__maps_E");
   E097 : Short_Integer; pragma Import (Ada, E097, "ada__strings__maps__constants_E");
   E049 : Short_Integer; pragma Import (Ada, E049, "ada__tags_E");
   E064 : Short_Integer; pragma Import (Ada, E064, "ada__streams_E");
   E075 : Short_Integer; pragma Import (Ada, E075, "interfaces__c_E");
   E023 : Short_Integer; pragma Import (Ada, E023, "system__exceptions_E");
   E080 : Short_Integer; pragma Import (Ada, E080, "system__file_control_block_E");
   E541 : Short_Integer; pragma Import (Ada, E541, "ada__streams__stream_io_E");
   E070 : Short_Integer; pragma Import (Ada, E070, "system__file_io_E");
   E073 : Short_Integer; pragma Import (Ada, E073, "system__finalization_root_E");
   E071 : Short_Integer; pragma Import (Ada, E071, "ada__finalization_E");
   E535 : Short_Integer; pragma Import (Ada, E535, "system__regpat_E");
   E178 : Short_Integer; pragma Import (Ada, E178, "system__storage_pools_E");
   E174 : Short_Integer; pragma Import (Ada, E174, "system__finalization_masters_E");
   E180 : Short_Integer; pragma Import (Ada, E180, "system__storage_pools__subpools_E");
   E508 : Short_Integer; pragma Import (Ada, E508, "system__task_info_E");
   E241 : Short_Integer; pragma Import (Ada, E241, "ada__calendar_E");
   E247 : Short_Integer; pragma Import (Ada, E247, "ada__calendar__time_zones_E");
   E801 : Short_Integer; pragma Import (Ada, E801, "ada__command_line__response_file_E");
   E087 : Short_Integer; pragma Import (Ada, E087, "gnat__directory_operations_E");
   E522 : Short_Integer; pragma Import (Ada, E522, "gnat__directory_operations__iteration_E");
   E145 : Short_Integer; pragma Import (Ada, E145, "system__assertions_E");
   E207 : Short_Integer; pragma Import (Ada, E207, "system__pool_global_E");
   E015 : Short_Integer; pragma Import (Ada, E015, "system__secondary_stack_E");
   E201 : Short_Integer; pragma Import (Ada, E201, "ada__strings__unbounded_E");
   E239 : Short_Integer; pragma Import (Ada, E239, "ada__directories_E");
   E530 : Short_Integer; pragma Import (Ada, E530, "gnat__expect_E");
   E212 : Short_Integer; pragma Import (Ada, E212, "system__regexp_E");
   E199 : Short_Integer; pragma Import (Ada, E199, "gnat__command_line_E");
   E492 : Short_Integer; pragma Import (Ada, E492, "ada__real_time_E");
   E062 : Short_Integer; pragma Import (Ada, E062, "ada__text_io_E");
   E462 : Short_Integer; pragma Import (Ada, E462, "gnat__io_aux_E");
   E131 : Short_Integer; pragma Import (Ada, E131, "charset_E");
   E107 : Short_Integer; pragma Import (Ada, E107, "ocarina_E");
   E871 : Short_Integer; pragma Import (Ada, E871, "ocarina__be_real_E");
   E799 : Short_Integer; pragma Import (Ada, E799, "ocarina__cmd_line_E");
   E857 : Short_Integer; pragma Import (Ada, E857, "ocarina__configuration_E");
   E803 : Short_Integer; pragma Import (Ada, E803, "ocarina__fe_aadl_E");
   E873 : Short_Integer; pragma Import (Ada, E873, "ocarina__fe_aadl_ba_E");
   E900 : Short_Integer; pragma Import (Ada, E900, "ocarina__fe_aadl_ema_E");
   E910 : Short_Integer; pragma Import (Ada, E910, "ocarina__fe_ao4aadl_E");
   E847 : Short_Integer; pragma Import (Ada, E847, "ocarina__fe_real_E");
   E855 : Short_Integer; pragma Import (Ada, E855, "ocarina__scripts_E");
   E143 : Short_Integer; pragma Import (Ada, E143, "ocarina__types_E");
   E157 : Short_Integer; pragma Import (Ada, E157, "locations_E");
   E082 : Short_Integer; pragma Import (Ada, E082, "errors_E");
   E215 : Short_Integer; pragma Import (Ada, E215, "ocarina__analyzer_E");
   E217 : Short_Integer; pragma Import (Ada, E217, "ocarina__analyzer__aadl_E");
   E219 : Short_Integer; pragma Import (Ada, E219, "ocarina__analyzer__aadl__annexes_E");
   E258 : Short_Integer; pragma Import (Ada, E258, "ocarina__analyzer__aadl__legality_rules_E");
   E260 : Short_Integer; pragma Import (Ada, E260, "ocarina__analyzer__aadl__links_E");
   E289 : Short_Integer; pragma Import (Ada, E289, "ocarina__analyzer__aadl__names_E");
   E223 : Short_Integer; pragma Import (Ada, E223, "ocarina__analyzer__aadl__naming_rules_E");
   E264 : Short_Integer; pragma Import (Ada, E264, "ocarina__analyzer__aadl__queries_E");
   E262 : Short_Integer; pragma Import (Ada, E262, "ocarina__analyzer__aadl__semantics_E");
   E295 : Short_Integer; pragma Import (Ada, E295, "ocarina__analyzer__aadl_ba_E");
   E304 : Short_Integer; pragma Import (Ada, E304, "ocarina__analyzer__aadl_ema_E");
   E310 : Short_Integer; pragma Import (Ada, E310, "ocarina__analyzer__aadl_ema__links_E");
   E308 : Short_Integer; pragma Import (Ada, E308, "ocarina__analyzer__aadl_ema__naming_rules_E");
   E319 : Short_Integer; pragma Import (Ada, E319, "ocarina__analyzer__real_E");
   E159 : Short_Integer; pragma Import (Ada, E159, "ocarina__annotations_E");
   E378 : Short_Integer; pragma Import (Ada, E378, "ocarina__backends_E");
   E380 : Short_Integer; pragma Import (Ada, E380, "ocarina__backends__aadl_xml_E");
   E382 : Short_Integer; pragma Import (Ada, E382, "ocarina__backends__aadl_xml__main_E");
   E384 : Short_Integer; pragma Import (Ada, E384, "ocarina__backends__aadl_xml__mapping_E");
   E679 : Short_Integer; pragma Import (Ada, E679, "ocarina__backends__ada_tree__generator_E");
   E398 : Short_Integer; pragma Import (Ada, E398, "ocarina__backends__ada_tree__nodes_E");
   E402 : Short_Integer; pragma Import (Ada, E402, "ocarina__backends__ada_tree__nutils_E");
   E406 : Short_Integer; pragma Import (Ada, E406, "ocarina__backends__ada_values_E");
   E420 : Short_Integer; pragma Import (Ada, E420, "ocarina__backends__alloy_E");
   E424 : Short_Integer; pragma Import (Ada, E424, "ocarina__backends__arinc653_conf_E");
   E426 : Short_Integer; pragma Import (Ada, E426, "ocarina__backends__arinc653_conf__connections_E");
   E433 : Short_Integer; pragma Import (Ada, E433, "ocarina__backends__arinc653_conf__memory_E");
   E435 : Short_Integer; pragma Import (Ada, E435, "ocarina__backends__arinc653_conf__module_hm_E");
   E437 : Short_Integer; pragma Import (Ada, E437, "ocarina__backends__arinc653_conf__partition_hm_E");
   E439 : Short_Integer; pragma Import (Ada, E439, "ocarina__backends__arinc653_conf__partitions_E");
   E441 : Short_Integer; pragma Import (Ada, E441, "ocarina__backends__arinc653_conf__scheduling_E");
   E443 : Short_Integer; pragma Import (Ada, E443, "ocarina__backends__arinc653_conf__system_hm_E");
   E445 : Short_Integer; pragma Import (Ada, E445, "ocarina__backends__asn1_E");
   E447 : Short_Integer; pragma Import (Ada, E447, "ocarina__backends__asn1__deployment_E");
   E458 : Short_Integer; pragma Import (Ada, E458, "ocarina__backends__asn1_tree__generator_E");
   E450 : Short_Integer; pragma Import (Ada, E450, "ocarina__backends__asn1_tree__nodes_E");
   E456 : Short_Integer; pragma Import (Ada, E456, "ocarina__backends__asn1_values_E");
   E454 : Short_Integer; pragma Import (Ada, E454, "ocarina__backends__asn1_tree__nutils_E");
   E460 : Short_Integer; pragma Import (Ada, E460, "ocarina__backends__boundt_E");
   E480 : Short_Integer; pragma Import (Ada, E480, "ocarina__backends__c_common__subprograms_E");
   E484 : Short_Integer; pragma Import (Ada, E484, "ocarina__backends__c_common__types_E");
   E488 : Short_Integer; pragma Import (Ada, E488, "ocarina__backends__c_tree__generator_E");
   E467 : Short_Integer; pragma Import (Ada, E467, "ocarina__backends__c_tree__nodes_E");
   E471 : Short_Integer; pragma Import (Ada, E471, "ocarina__backends__c_tree__nutils_E");
   E476 : Short_Integer; pragma Import (Ada, E476, "ocarina__backends__c_values_E");
   E571 : Short_Integer; pragma Import (Ada, E571, "ocarina__backends__cheddar_E");
   E573 : Short_Integer; pragma Import (Ada, E573, "ocarina__backends__cheddar__main_E");
   E577 : Short_Integer; pragma Import (Ada, E577, "ocarina__backends__connection_matrix_E");
   E579 : Short_Integer; pragma Import (Ada, E579, "ocarina__backends__connection_matrix__main_E");
   E581 : Short_Integer; pragma Import (Ada, E581, "ocarina__backends__deos_conf_E");
   E583 : Short_Integer; pragma Import (Ada, E583, "ocarina__backends__deos_conf__hm_E");
   E585 : Short_Integer; pragma Import (Ada, E585, "ocarina__backends__deos_conf__naming_E");
   E589 : Short_Integer; pragma Import (Ada, E589, "ocarina__backends__deos_conf__partitions_E");
   E607 : Short_Integer; pragma Import (Ada, E607, "ocarina__backends__deos_conf__schedule_E");
   E416 : Short_Integer; pragma Import (Ada, E416, "ocarina__backends__expander_E");
   E611 : Short_Integer; pragma Import (Ada, E611, "ocarina__backends__functions_matrix_E");
   E613 : Short_Integer; pragma Import (Ada, E613, "ocarina__backends__functions_matrix__main_E");
   E641 : Short_Integer; pragma Import (Ada, E641, "ocarina__backends__mast_E");
   E643 : Short_Integer; pragma Import (Ada, E643, "ocarina__backends__mast__main_E");
   E654 : Short_Integer; pragma Import (Ada, E654, "ocarina__backends__mast_tree__generator_E");
   E646 : Short_Integer; pragma Import (Ada, E646, "ocarina__backends__mast_tree__nodes_E");
   E652 : Short_Integer; pragma Import (Ada, E652, "ocarina__backends__mast_tree__nutils_E");
   E650 : Short_Integer; pragma Import (Ada, E650, "ocarina__backends__mast_values_E");
   E408 : Short_Integer; pragma Import (Ada, E408, "ocarina__backends__messages_E");
   E656 : Short_Integer; pragma Import (Ada, E656, "ocarina__backends__pn_E");
   E658 : Short_Integer; pragma Import (Ada, E658, "ocarina__backends__pn__components_E");
   E671 : Short_Integer; pragma Import (Ada, E671, "ocarina__backends__pn__format__cami_E");
   E673 : Short_Integer; pragma Import (Ada, E673, "ocarina__backends__pn__format__tina_E");
   E664 : Short_Integer; pragma Import (Ada, E664, "ocarina__backends__pn__iutils_E");
   E662 : Short_Integer; pragma Import (Ada, E662, "ocarina__backends__pn__nodes_E");
   E666 : Short_Integer; pragma Import (Ada, E666, "ocarina__backends__pn__nutils_E");
   E675 : Short_Integer; pragma Import (Ada, E675, "ocarina__backends__pn__printer_E");
   E668 : Short_Integer; pragma Import (Ada, E668, "ocarina__backends__pn__utils_E");
   E677 : Short_Integer; pragma Import (Ada, E677, "ocarina__backends__po_hi_ada_E");
   E681 : Short_Integer; pragma Import (Ada, E681, "ocarina__backends__po_hi_ada__activity_E");
   E687 : Short_Integer; pragma Import (Ada, E687, "ocarina__backends__po_hi_ada__deployment_E");
   E689 : Short_Integer; pragma Import (Ada, E689, "ocarina__backends__po_hi_ada__main_E");
   E691 : Short_Integer; pragma Import (Ada, E691, "ocarina__backends__po_hi_ada__marshallers_E");
   E693 : Short_Integer; pragma Import (Ada, E693, "ocarina__backends__po_hi_ada__naming_E");
   E685 : Short_Integer; pragma Import (Ada, E685, "ocarina__backends__po_hi_ada__runtime_E");
   E695 : Short_Integer; pragma Import (Ada, E695, "ocarina__backends__po_hi_ada__subprograms_E");
   E697 : Short_Integer; pragma Import (Ada, E697, "ocarina__backends__po_hi_ada__transport_E");
   E699 : Short_Integer; pragma Import (Ada, E699, "ocarina__backends__po_hi_ada__types_E");
   E478 : Short_Integer; pragma Import (Ada, E478, "ocarina__backends__po_hi_c_E");
   E559 : Short_Integer; pragma Import (Ada, E559, "ocarina__backends__po_hi_c__activity_E");
   E561 : Short_Integer; pragma Import (Ada, E561, "ocarina__backends__po_hi_c__deployment_E");
   E563 : Short_Integer; pragma Import (Ada, E563, "ocarina__backends__po_hi_c__main_E");
   E565 : Short_Integer; pragma Import (Ada, E565, "ocarina__backends__po_hi_c__marshallers_E");
   E567 : Short_Integer; pragma Import (Ada, E567, "ocarina__backends__po_hi_c__naming_E");
   E569 : Short_Integer; pragma Import (Ada, E569, "ocarina__backends__po_hi_c__request_E");
   E482 : Short_Integer; pragma Import (Ada, E482, "ocarina__backends__po_hi_c__runtime_E");
   E486 : Short_Integer; pragma Import (Ada, E486, "ocarina__backends__pok_c_E");
   E545 : Short_Integer; pragma Import (Ada, E545, "ocarina__backends__pok_c__activity_E");
   E549 : Short_Integer; pragma Import (Ada, E549, "ocarina__backends__pok_c__deployment_E");
   E551 : Short_Integer; pragma Import (Ada, E551, "ocarina__backends__pok_c__main_E");
   E553 : Short_Integer; pragma Import (Ada, E553, "ocarina__backends__pok_c__makefile_E");
   E555 : Short_Integer; pragma Import (Ada, E555, "ocarina__backends__pok_c__naming_E");
   E547 : Short_Integer; pragma Import (Ada, E547, "ocarina__backends__pok_c__runtime_E");
   E557 : Short_Integer; pragma Import (Ada, E557, "ocarina__backends__pok_cheddar_E");
   E412 : Short_Integer; pragma Import (Ada, E412, "ocarina__backends__properties_E");
   E428 : Short_Integer; pragma Import (Ada, E428, "ocarina__backends__arinc653_conf__mapping_E");
   E464 : Short_Integer; pragma Import (Ada, E464, "ocarina__backends__build_utils_E");
   E474 : Short_Integer; pragma Import (Ada, E474, "ocarina__backends__c_common__mapping_E");
   E587 : Short_Integer; pragma Import (Ada, E587, "ocarina__backends__deos_conf__mapping_E");
   E490 : Short_Integer; pragma Import (Ada, E490, "ocarina__backends__execution_tests_E");
   E524 : Short_Integer; pragma Import (Ada, E524, "ocarina__backends__execution_utils_E");
   E615 : Short_Integer; pragma Import (Ada, E615, "ocarina__backends__lnt_E");
   E617 : Short_Integer; pragma Import (Ada, E617, "ocarina__backends__lnt__nodes_E");
   E631 : Short_Integer; pragma Import (Ada, E631, "ocarina__backends__lnt__components_E");
   E621 : Short_Integer; pragma Import (Ada, E621, "ocarina__backends__lnt__nutils_E");
   E623 : Short_Integer; pragma Import (Ada, E623, "ocarina__backends__lnt__printer_E");
   E625 : Short_Integer; pragma Import (Ada, E625, "ocarina__backends__lnt__svl_generator_E");
   E627 : Short_Integer; pragma Import (Ada, E627, "ocarina__backends__lnt__tree_generator_E");
   E629 : Short_Integer; pragma Import (Ada, E629, "ocarina__backends__lnt__tree_generator_main_E");
   E633 : Short_Integer; pragma Import (Ada, E633, "ocarina__backends__lnt__tree_generator_port_E");
   E635 : Short_Integer; pragma Import (Ada, E635, "ocarina__backends__lnt__tree_generator_processor_E");
   E637 : Short_Integer; pragma Import (Ada, E637, "ocarina__backends__lnt__tree_generator_thread_E");
   E639 : Short_Integer; pragma Import (Ada, E639, "ocarina__backends__lnt__tree_generator_types_E");
   E683 : Short_Integer; pragma Import (Ada, E683, "ocarina__backends__po_hi_ada__mapping_E");
   E609 : Short_Integer; pragma Import (Ada, E609, "ocarina__backends__properties__arinc653_E");
   E757 : Short_Integer; pragma Import (Ada, E757, "ocarina__backends__replication_properties_E");
   E723 : Short_Integer; pragma Import (Ada, E723, "ocarina__backends__replication_expander_E");
   E759 : Short_Integer; pragma Import (Ada, E759, "ocarina__backends__stats_E");
   E761 : Short_Integer; pragma Import (Ada, E761, "ocarina__backends__stats__main_E");
   E763 : Short_Integer; pragma Import (Ada, E763, "ocarina__backends__stats__mapping_E");
   E765 : Short_Integer; pragma Import (Ada, E765, "ocarina__backends__subprograms_E");
   E395 : Short_Integer; pragma Import (Ada, E395, "ocarina__backends__utils_E");
   E767 : Short_Integer; pragma Import (Ada, E767, "ocarina__backends__vxworks653_conf_E");
   E769 : Short_Integer; pragma Import (Ada, E769, "ocarina__backends__vxworks653_conf__connections_E");
   E773 : Short_Integer; pragma Import (Ada, E773, "ocarina__backends__vxworks653_conf__hm_E");
   E771 : Short_Integer; pragma Import (Ada, E771, "ocarina__backends__vxworks653_conf__mapping_E");
   E775 : Short_Integer; pragma Import (Ada, E775, "ocarina__backends__vxworks653_conf__naming_E");
   E777 : Short_Integer; pragma Import (Ada, E777, "ocarina__backends__vxworks653_conf__partitions_E");
   E779 : Short_Integer; pragma Import (Ada, E779, "ocarina__backends__vxworks653_conf__payloads_E");
   E781 : Short_Integer; pragma Import (Ada, E781, "ocarina__backends__vxworks653_conf__schedule_E");
   E431 : Short_Integer; pragma Import (Ada, E431, "ocarina__backends__xml_common__mapping_E");
   E418 : Short_Integer; pragma Import (Ada, E418, "ocarina__backends__xml_tree__generator_E");
   E387 : Short_Integer; pragma Import (Ada, E387, "ocarina__backends__xml_tree__nodes_E");
   E393 : Short_Integer; pragma Import (Ada, E393, "ocarina__backends__xml_tree__nutils_E");
   E391 : Short_Integer; pragma Import (Ada, E391, "ocarina__backends__xml_values_E");
   E783 : Short_Integer; pragma Import (Ada, E783, "ocarina__backends__xtratum_conf_E");
   E785 : Short_Integer; pragma Import (Ada, E785, "ocarina__backends__xtratum_conf__channels_E");
   E787 : Short_Integer; pragma Import (Ada, E787, "ocarina__backends__xtratum_conf__hardware_description_E");
   E795 : Short_Integer; pragma Import (Ada, E795, "ocarina__backends__xtratum_conf__mapping_E");
   E789 : Short_Integer; pragma Import (Ada, E789, "ocarina__backends__xtratum_conf__partition_table_E");
   E791 : Short_Integer; pragma Import (Ada, E791, "ocarina__backends__xtratum_conf__resident_sw_E");
   E793 : Short_Integer; pragma Import (Ada, E793, "ocarina__backends__xtratum_conf__system_description_E");
   E797 : Short_Integer; pragma Import (Ada, E797, "ocarina__backends__xtratum_conf__xm_hypervisor_E");
   E813 : Short_Integer; pragma Import (Ada, E813, "ocarina__builder__aadl__annexes_E");
   E273 : Short_Integer; pragma Import (Ada, E273, "ocarina__builder__aadl__components_E");
   E829 : Short_Integer; pragma Import (Ada, E829, "ocarina__builder__aadl__components__arrays_E");
   E277 : Short_Integer; pragma Import (Ada, E277, "ocarina__builder__aadl__components__connections_E");
   E279 : Short_Integer; pragma Import (Ada, E279, "ocarina__builder__aadl__components__features_E");
   E281 : Short_Integer; pragma Import (Ada, E281, "ocarina__builder__aadl__components__flows_E");
   E283 : Short_Integer; pragma Import (Ada, E283, "ocarina__builder__aadl__components__modes_E");
   E837 : Short_Integer; pragma Import (Ada, E837, "ocarina__builder__aadl__components__prototypes_E");
   E285 : Short_Integer; pragma Import (Ada, E285, "ocarina__builder__aadl__components__subcomponents_E");
   E287 : Short_Integer; pragma Import (Ada, E287, "ocarina__builder__aadl__components__subprogram_calls_E");
   E275 : Short_Integer; pragma Import (Ada, E275, "ocarina__builder__aadl__namespaces_E");
   E271 : Short_Integer; pragma Import (Ada, E271, "ocarina__builder__aadl__properties_E");
   E886 : Short_Integer; pragma Import (Ada, E886, "ocarina__builder__aadl_ba__actions_E");
   E890 : Short_Integer; pragma Import (Ada, E890, "ocarina__builder__aadl_ba__expressions_E");
   E882 : Short_Integer; pragma Import (Ada, E882, "ocarina__builder__aadl_ba__specifications_E");
   E896 : Short_Integer; pragma Import (Ada, E896, "ocarina__builder__aadl_ba__thread_dispatch_E");
   E323 : Short_Integer; pragma Import (Ada, E323, "ocarina__builder__real_E");
   E902 : Short_Integer; pragma Import (Ada, E902, "ocarina__fe_aadl_ema__parser_E");
   E912 : Short_Integer; pragma Import (Ada, E912, "ocarina__fe_ao4aadl__parser_E");
   E849 : Short_Integer; pragma Import (Ada, E849, "ocarina__fe_real__parser_E");
   E237 : Short_Integer; pragma Import (Ada, E237, "ocarina__files_E");
   E334 : Short_Integer; pragma Import (Ada, E334, "ocarina__instances_E");
   E338 : Short_Integer; pragma Import (Ada, E338, "ocarina__instances__annexes_E");
   E336 : Short_Integer; pragma Import (Ada, E336, "ocarina__instances__components_E");
   E340 : Short_Integer; pragma Import (Ada, E340, "ocarina__instances__components__connections_E");
   E354 : Short_Integer; pragma Import (Ada, E354, "ocarina__instances__components__features_E");
   E344 : Short_Integer; pragma Import (Ada, E344, "ocarina__instances__components__modes_E");
   E356 : Short_Integer; pragma Import (Ada, E356, "ocarina__instances__components__subcomponents_E");
   E346 : Short_Integer; pragma Import (Ada, E346, "ocarina__instances__components__subprogram_calls_E");
   E348 : Short_Integer; pragma Import (Ada, E348, "ocarina__instances__messages_E");
   E350 : Short_Integer; pragma Import (Ada, E350, "ocarina__instances__namespaces_E");
   E359 : Short_Integer; pragma Import (Ada, E359, "ocarina__instances__processor__properties_E");
   E342 : Short_Integer; pragma Import (Ada, E342, "ocarina__instances__properties_E");
   E364 : Short_Integer; pragma Import (Ada, E364, "ocarina__instances__queries_E");
   E362 : Short_Integer; pragma Import (Ada, E362, "ocarina__instances__real_checker__queries_E");
   E701 : Short_Integer; pragma Import (Ada, E701, "ocarina__backends__real_E");
   E705 : Short_Integer; pragma Import (Ada, E705, "ocarina__instances__real_checker__queries__relational_predicates_E");
   E189 : Short_Integer; pragma Import (Ada, E189, "ocarina__me_aadl__aadl_instances__entities_E");
   E193 : Short_Integer; pragma Import (Ada, E193, "ocarina__me_aadl__aadl_instances__nodes_E");
   E187 : Short_Integer; pragma Import (Ada, E187, "ocarina__me_aadl__aadl_instances__nutils_E");
   E352 : Short_Integer; pragma Import (Ada, E352, "ocarina__instances__finder_E");
   E422 : Short_Integer; pragma Import (Ada, E422, "ocarina__backends__helper_E");
   E575 : Short_Integer; pragma Import (Ada, E575, "ocarina__backends__cheddar__mapping_E");
   E195 : Short_Integer; pragma Import (Ada, E195, "ocarina__me_aadl__aadl_tree__entities_E");
   E153 : Short_Integer; pragma Import (Ada, E153, "ocarina__me_aadl__aadl_tree__nodes_E");
   E109 : Short_Integer; pragma Import (Ada, E109, "ocarina__aadl_values_E");
   E221 : Short_Integer; pragma Import (Ada, E221, "ocarina__analyzer__aadl__finder_E");
   E225 : Short_Integer; pragma Import (Ada, E225, "ocarina__analyzer__messages_E");
   E414 : Short_Integer; pragma Import (Ada, E414, "ocarina__backends__properties__utils_E");
   E366 : Short_Integer; pragma Import (Ada, E366, "ocarina__me_aadl__aadl_instances__entities__properties_E");
   E227 : Short_Integer; pragma Import (Ada, E227, "ocarina__me_aadl__aadl_tree__entities__properties_E");
   E197 : Short_Integer; pragma Import (Ada, E197, "ocarina__me_aadl__aadl_tree__nutils_E");
   E291 : Short_Integer; pragma Import (Ada, E291, "ocarina__me_aadl__printers_E");
   E298 : Short_Integer; pragma Import (Ada, E298, "ocarina__me_aadl_ba__ba_tree__nodes_E");
   E302 : Short_Integer; pragma Import (Ada, E302, "ocarina__me_aadl_ba__ba_tree__nutils_E");
   E235 : Short_Integer; pragma Import (Ada, E235, "ocarina__me_aadl_ema__ema_tokens_E");
   E908 : Short_Integer; pragma Import (Ada, E908, "ocarina__fe_aadl_ema__parser_errors_E");
   E313 : Short_Integer; pragma Import (Ada, E313, "ocarina__me_aadl_ema__ema_tree__nodes_E");
   E306 : Short_Integer; pragma Import (Ada, E306, "ocarina__analyzer__aadl_ema__finder_E");
   E904 : Short_Integer; pragma Import (Ada, E904, "ocarina__ema_values_E");
   E317 : Short_Integer; pragma Import (Ada, E317, "ocarina__me_aadl_ema__ema_tree__nutils_E");
   E920 : Short_Integer; pragma Import (Ada, E920, "ocarina__me_ao4aadl__ao4aadl_tree__nodes_E");
   E914 : Short_Integer; pragma Import (Ada, E914, "ocarina__ao4aadl_values_E");
   E918 : Short_Integer; pragma Import (Ada, E918, "ocarina__me_ao4aadl__ao4aadl_tree__nutils_E");
   E926 : Short_Integer; pragma Import (Ada, E926, "ocarina__me_ao4aadl__tokens_E");
   E928 : Short_Integer; pragma Import (Ada, E928, "ocarina__fe_ao4aadl__parser_errors_E");
   E326 : Short_Integer; pragma Import (Ada, E326, "ocarina__me_real__real_tree__nodes_E");
   E332 : Short_Integer; pragma Import (Ada, E332, "ocarina__me_real__real_tree__nutils_E");
   E321 : Short_Integer; pragma Import (Ada, E321, "ocarina__analyzer__real__finder_E");
   E256 : Short_Integer; pragma Import (Ada, E256, "ocarina__me_real__tokens_E");
   E853 : Short_Integer; pragma Import (Ada, E853, "ocarina__fe_real__parser_errors_E");
   E135 : Short_Integer; pragma Import (Ada, E135, "ocarina__namet_E");
   E906 : Short_Integer; pragma Import (Ada, E906, "ocarina__fe_aadl_ema__lexer_E");
   E924 : Short_Integer; pragma Import (Ada, E924, "ocarina__fe_ao4aadl__lexer_E");
   E851 : Short_Integer; pragma Import (Ada, E851, "ocarina__fe_real__lexer_E");
   E755 : Short_Integer; pragma Import (Ada, E755, "ocarina__me_aadl__tokens_E");
   E725 : Short_Integer; pragma Import (Ada, E725, "ocarina__be_aadl_E");
   E729 : Short_Integer; pragma Import (Ada, E729, "ocarina__be_aadl__annexes_E");
   E727 : Short_Integer; pragma Import (Ada, E727, "ocarina__be_aadl__components_E");
   E739 : Short_Integer; pragma Import (Ada, E739, "ocarina__be_aadl__components__arrays_E");
   E741 : Short_Integer; pragma Import (Ada, E741, "ocarina__be_aadl__components__connections_E");
   E743 : Short_Integer; pragma Import (Ada, E743, "ocarina__be_aadl__components__features_E");
   E745 : Short_Integer; pragma Import (Ada, E745, "ocarina__be_aadl__components__flows_E");
   E731 : Short_Integer; pragma Import (Ada, E731, "ocarina__be_aadl__components__modes_E");
   E747 : Short_Integer; pragma Import (Ada, E747, "ocarina__be_aadl__components__prototypes_E");
   E749 : Short_Integer; pragma Import (Ada, E749, "ocarina__be_aadl__components__subcomponents_E");
   E751 : Short_Integer; pragma Import (Ada, E751, "ocarina__be_aadl__components__subprogram_calls_E");
   E733 : Short_Integer; pragma Import (Ada, E733, "ocarina__be_aadl__identifiers_E");
   E753 : Short_Integer; pragma Import (Ada, E753, "ocarina__be_aadl__namespaces_E");
   E735 : Short_Integer; pragma Import (Ada, E735, "ocarina__be_aadl__properties_E");
   E737 : Short_Integer; pragma Import (Ada, E737, "ocarina__be_aadl__properties__values_E");
   E807 : Short_Integer; pragma Import (Ada, E807, "ocarina__fe_aadl__lexer_E");
   E845 : Short_Integer; pragma Import (Ada, E845, "ocarina__fe_aadl__parser_errors_E");
   E805 : Short_Integer; pragma Import (Ada, E805, "ocarina__fe_aadl__parser_E");
   E811 : Short_Integer; pragma Import (Ada, E811, "ocarina__fe_aadl__parser__annexes_E");
   E815 : Short_Integer; pragma Import (Ada, E815, "ocarina__fe_aadl__parser__components_E");
   E827 : Short_Integer; pragma Import (Ada, E827, "ocarina__fe_aadl__parser__components__arrays_E");
   E817 : Short_Integer; pragma Import (Ada, E817, "ocarina__fe_aadl__parser__components__connections_E");
   E831 : Short_Integer; pragma Import (Ada, E831, "ocarina__fe_aadl__parser__components__features_E");
   E833 : Short_Integer; pragma Import (Ada, E833, "ocarina__fe_aadl__parser__components__flows_E");
   E819 : Short_Integer; pragma Import (Ada, E819, "ocarina__fe_aadl__parser__components__modes_E");
   E835 : Short_Integer; pragma Import (Ada, E835, "ocarina__fe_aadl__parser__components__prototypes_E");
   E839 : Short_Integer; pragma Import (Ada, E839, "ocarina__fe_aadl__parser__components__subcomponents_E");
   E841 : Short_Integer; pragma Import (Ada, E841, "ocarina__fe_aadl__parser__components__subprogram_calls_E");
   E821 : Short_Integer; pragma Import (Ada, E821, "ocarina__fe_aadl__parser__identifiers_E");
   E809 : Short_Integer; pragma Import (Ada, E809, "ocarina__fe_aadl__parser__namespaces_E");
   E823 : Short_Integer; pragma Import (Ada, E823, "ocarina__fe_aadl__parser__properties_E");
   E825 : Short_Integer; pragma Import (Ada, E825, "ocarina__fe_aadl__parser__properties__values_E");
   E232 : Short_Integer; pragma Import (Ada, E232, "ocarina__me_aadl_ba__tokens_E");
   E859 : Short_Integer; pragma Import (Ada, E859, "ocarina__be_aadl_ba_E");
   E863 : Short_Integer; pragma Import (Ada, E863, "ocarina__be_aadl_ba__actions_E");
   E865 : Short_Integer; pragma Import (Ada, E865, "ocarina__be_aadl_ba__expressions_E");
   E867 : Short_Integer; pragma Import (Ada, E867, "ocarina__be_aadl_ba__identifiers_E");
   E861 : Short_Integer; pragma Import (Ada, E861, "ocarina__be_aadl_ba__specifications_E");
   E869 : Short_Integer; pragma Import (Ada, E869, "ocarina__be_aadl_ba__thread_dispatch_E");
   E877 : Short_Integer; pragma Import (Ada, E877, "ocarina__fe_aadl_ba__lexer_E");
   E898 : Short_Integer; pragma Import (Ada, E898, "ocarina__fe_aadl_ba__parser_errors_E");
   E875 : Short_Integer; pragma Import (Ada, E875, "ocarina__fe_aadl_ba__parser_E");
   E884 : Short_Integer; pragma Import (Ada, E884, "ocarina__fe_aadl_ba__parser__actions_E");
   E888 : Short_Integer; pragma Import (Ada, E888, "ocarina__fe_aadl_ba__parser__expressions_E");
   E892 : Short_Integer; pragma Import (Ada, E892, "ocarina__fe_aadl_ba__parser__identifiers_E");
   E879 : Short_Integer; pragma Import (Ada, E879, "ocarina__fe_aadl_ba__parser__specifications_E");
   E894 : Short_Integer; pragma Import (Ada, E894, "ocarina__fe_aadl_ba__parser__thread_dispatch_E");
   E253 : Short_Integer; pragma Import (Ada, E253, "ocarina__options_E");
   E141 : Short_Integer; pragma Import (Ada, E141, "ocarina__output_E");
   E400 : Short_Integer; pragma Import (Ada, E400, "ocarina__backends__ada_tree__debug_E");
   E452 : Short_Integer; pragma Import (Ada, E452, "ocarina__backends__asn1_tree__debug_E");
   E469 : Short_Integer; pragma Import (Ada, E469, "ocarina__backends__c_tree__debug_E");
   E619 : Short_Integer; pragma Import (Ada, E619, "ocarina__backends__lnt__debug_E");
   E648 : Short_Integer; pragma Import (Ada, E648, "ocarina__backends__mast_tree__debug_E");
   E660 : Short_Integer; pragma Import (Ada, E660, "ocarina__backends__pn__debug_E");
   E389 : Short_Integer; pragma Import (Ada, E389, "ocarina__backends__xml_tree__debug_E");
   E191 : Short_Integer; pragma Import (Ada, E191, "ocarina__me_aadl__aadl_instances__debug_E");
   E155 : Short_Integer; pragma Import (Ada, E155, "ocarina__me_aadl__aadl_tree__debug_E");
   E300 : Short_Integer; pragma Import (Ada, E300, "ocarina__me_aadl_ba__ba_tree__debug_E");
   E315 : Short_Integer; pragma Import (Ada, E315, "ocarina__me_aadl_ema__ema_tree__debug_E");
   E922 : Short_Integer; pragma Import (Ada, E922, "ocarina__me_ao4aadl__ao4aadl_tree__debug_E");
   E328 : Short_Integer; pragma Import (Ada, E328, "ocarina__me_real__real_tree__debug_E");
   E330 : Short_Integer; pragma Import (Ada, E330, "ocarina__me_real__real_tree__utils_E");
   E721 : Short_Integer; pragma Import (Ada, E721, "ocarina__instances__real_finder_E");
   E843 : Short_Integer; pragma Import (Ada, E843, "ocarina__parser_E");
   E267 : Short_Integer; pragma Import (Ada, E267, "ocarina__processor__properties_E");
   E229 : Short_Integer; pragma Import (Ada, E229, "ocarina__property_sets_E");
   E374 : Short_Integer; pragma Import (Ada, E374, "ocarina__real_expander_E");
   E376 : Short_Integer; pragma Import (Ada, E376, "ocarina__real_expander__flow_analysis_E");
   E368 : Short_Integer; pragma Import (Ada, E368, "ocarina__real_values_E");
   E930 : Short_Integer; pragma Import (Ada, E930, "ocarina__transfo_E");
   E932 : Short_Integer; pragma Import (Ada, E932, "ocarina__transfo__fusions_E");
   E934 : Short_Integer; pragma Import (Ada, E934, "ocarina__transfo__fusions__scheduler_E");
   E936 : Short_Integer; pragma Import (Ada, E936, "ocarina__transfo__move_E");
   E938 : Short_Integer; pragma Import (Ada, E938, "ocarina__transfo__optim_E");
   E940 : Short_Integer; pragma Import (Ada, E940, "ocarina__transfo__optim__eval_E");
   E942 : Short_Integer; pragma Import (Ada, E942, "ocarina__utils_E");
   E293 : Short_Integer; pragma Import (Ada, E293, "outfiles_E");
   E163 : Short_Integer; pragma Import (Ada, E163, "utils_E");
   E703 : Short_Integer; pragma Import (Ada, E703, "ocarina__instances__real_checker__queries__access_predicates_E");
   E707 : Short_Integer; pragma Import (Ada, E707, "ocarina__instances__real_checker__queries__bound_predicates_E");
   E709 : Short_Integer; pragma Import (Ada, E709, "ocarina__instances__real_checker__queries__call_predicates_E");
   E711 : Short_Integer; pragma Import (Ada, E711, "ocarina__instances__real_checker__queries__connected_predicates_E");
   E713 : Short_Integer; pragma Import (Ada, E713, "ocarina__instances__real_checker__queries__passing_predicates_E");
   E715 : Short_Integer; pragma Import (Ada, E715, "ocarina__instances__real_checker__queries__predecessor_predicates_E");
   E717 : Short_Integer; pragma Import (Ada, E717, "ocarina__instances__real_checker__queries__provided_class_predicates_E");
   E719 : Short_Integer; pragma Import (Ada, E719, "ocarina__instances__real_checker__queries__subcomponent_predicates_E");

   Local_Priority_Specific_Dispatching : constant String := "";
   Local_Interrupt_States : constant String := "";

   Is_Elaborated : Boolean := False;

   procedure finalize_library is
   begin
      E163 := E163 - 1;
      declare
         procedure F1;
         pragma Import (Ada, F1, "utils__finalize_spec");
      begin
         F1;
      end;
      declare
         procedure F2;
         pragma Import (Ada, F2, "ocarina__backends__execution_tests__finalize_body");
      begin
         E490 := E490 - 1;
         F2;
      end;
      declare
         procedure F3;
         pragma Import (Ada, F3, "ocarina__backends__execution_tests__finalize_spec");
      begin
         F3;
      end;
      E062 := E062 - 1;
      declare
         procedure F4;
         pragma Import (Ada, F4, "ada__text_io__finalize_spec");
      begin
         F4;
      end;
      E239 := E239 - 1;
      E212 := E212 - 1;
      declare
         procedure F5;
         pragma Import (Ada, F5, "system__regexp__finalize_spec");
      begin
         F5;
      end;
      E530 := E530 - 1;
      declare
         procedure F6;
         pragma Import (Ada, F6, "gnat__expect__finalize_spec");
      begin
         F6;
      end;
      declare
         procedure F7;
         pragma Import (Ada, F7, "ada__directories__finalize_spec");
      begin
         F7;
      end;
      E201 := E201 - 1;
      declare
         procedure F8;
         pragma Import (Ada, F8, "ada__strings__unbounded__finalize_spec");
      begin
         F8;
      end;
      declare
         procedure F9;
         pragma Import (Ada, F9, "system__file_io__finalize_body");
      begin
         E070 := E070 - 1;
         F9;
      end;
      E174 := E174 - 1;
      E180 := E180 - 1;
      E207 := E207 - 1;
      declare
         procedure F10;
         pragma Import (Ada, F10, "system__pool_global__finalize_spec");
      begin
         F10;
      end;
      declare
         procedure F11;
         pragma Import (Ada, F11, "system__storage_pools__subpools__finalize_spec");
      begin
         F11;
      end;
      declare
         procedure F12;
         pragma Import (Ada, F12, "system__finalization_masters__finalize_spec");
      begin
         F12;
      end;
      E541 := E541 - 1;
      declare
         procedure F13;
         pragma Import (Ada, F13, "ada__streams__stream_io__finalize_spec");
      begin
         F13;
      end;
      declare
         procedure Reraise_Library_Exception_If_Any;
            pragma Import (Ada, Reraise_Library_Exception_If_Any, "__gnat_reraise_library_exception_if_any");
      begin
         Reraise_Library_Exception_If_Any;
      end;
   end finalize_library;

   procedure adafinal is
      procedure s_stalib_adafinal;
      pragma Import (C, s_stalib_adafinal, "system__standard_library__adafinal");

      procedure Runtime_Finalize;
      pragma Import (C, Runtime_Finalize, "__gnat_runtime_finalize");

   begin
      if not Is_Elaborated then
         return;
      end if;
      Is_Elaborated := False;
      Runtime_Finalize;
      s_stalib_adafinal;
   end adafinal;

   type No_Param_Proc is access procedure;

   procedure adainit is
      Main_Priority : Integer;
      pragma Import (C, Main_Priority, "__gl_main_priority");
      Time_Slice_Value : Integer;
      pragma Import (C, Time_Slice_Value, "__gl_time_slice_val");
      WC_Encoding : Character;
      pragma Import (C, WC_Encoding, "__gl_wc_encoding");
      Locking_Policy : Character;
      pragma Import (C, Locking_Policy, "__gl_locking_policy");
      Queuing_Policy : Character;
      pragma Import (C, Queuing_Policy, "__gl_queuing_policy");
      Task_Dispatching_Policy : Character;
      pragma Import (C, Task_Dispatching_Policy, "__gl_task_dispatching_policy");
      Priority_Specific_Dispatching : System.Address;
      pragma Import (C, Priority_Specific_Dispatching, "__gl_priority_specific_dispatching");
      Num_Specific_Dispatching : Integer;
      pragma Import (C, Num_Specific_Dispatching, "__gl_num_specific_dispatching");
      Main_CPU : Integer;
      pragma Import (C, Main_CPU, "__gl_main_cpu");
      Interrupt_States : System.Address;
      pragma Import (C, Interrupt_States, "__gl_interrupt_states");
      Num_Interrupt_States : Integer;
      pragma Import (C, Num_Interrupt_States, "__gl_num_interrupt_states");
      Unreserve_All_Interrupts : Integer;
      pragma Import (C, Unreserve_All_Interrupts, "__gl_unreserve_all_interrupts");
      Detect_Blocking : Integer;
      pragma Import (C, Detect_Blocking, "__gl_detect_blocking");
      Default_Stack_Size : Integer;
      pragma Import (C, Default_Stack_Size, "__gl_default_stack_size");
      Leap_Seconds_Support : Integer;
      pragma Import (C, Leap_Seconds_Support, "__gl_leap_seconds_support");
      Bind_Env_Addr : System.Address;
      pragma Import (C, Bind_Env_Addr, "__gl_bind_env_addr");

      procedure Runtime_Initialize (Install_Handler : Integer);
      pragma Import (C, Runtime_Initialize, "__gnat_runtime_initialize");

      Finalize_Library_Objects : No_Param_Proc;
      pragma Import (C, Finalize_Library_Objects, "__gnat_finalize_library_objects");
   begin
      if Is_Elaborated then
         return;
      end if;
      Is_Elaborated := True;
      Main_Priority := -1;
      Time_Slice_Value := -1;
      WC_Encoding := 'b';
      Locking_Policy := ' ';
      Queuing_Policy := ' ';
      Task_Dispatching_Policy := ' ';
      Priority_Specific_Dispatching :=
        Local_Priority_Specific_Dispatching'Address;
      Num_Specific_Dispatching := 0;
      Main_CPU := -1;
      Interrupt_States := Local_Interrupt_States'Address;
      Num_Interrupt_States := 0;
      Unreserve_All_Interrupts := 0;
      Detect_Blocking := 0;
      Default_Stack_Size := -1;
      Leap_Seconds_Support := 0;

      Runtime_Initialize (1);

      System.Scalar_Values.Initialize ('I', 'N');

      Finalize_Library_Objects := finalize_library'access;

      System.Soft_Links'Elab_Spec;
      System.Exception_Table'Elab_Body;
      E021 := E021 + 1;
      Ada.Containers'Elab_Spec;
      E164 := E164 + 1;
      Ada.Io_Exceptions'Elab_Spec;
      E065 := E065 + 1;
      Ada.Numerics'Elab_Spec;
      E369 := E369 + 1;
      Ada.Strings'Elab_Spec;
      E092 := E092 + 1;
      Ada.Strings.Maps'Elab_Spec;
      Ada.Strings.Maps.Constants'Elab_Spec;
      E097 := E097 + 1;
      Ada.Tags'Elab_Spec;
      Ada.Streams'Elab_Spec;
      E064 := E064 + 1;
      Interfaces.C'Elab_Spec;
      System.Exceptions'Elab_Spec;
      E023 := E023 + 1;
      System.File_Control_Block'Elab_Spec;
      E080 := E080 + 1;
      Ada.Streams.Stream_Io'Elab_Spec;
      E541 := E541 + 1;
      System.Finalization_Root'Elab_Spec;
      E073 := E073 + 1;
      Ada.Finalization'Elab_Spec;
      E071 := E071 + 1;
      System.Regpat'Elab_Spec;
      System.Storage_Pools'Elab_Spec;
      E178 := E178 + 1;
      System.Finalization_Masters'Elab_Spec;
      System.Storage_Pools.Subpools'Elab_Spec;
      System.Task_Info'Elab_Spec;
      E508 := E508 + 1;
      Ada.Calendar'Elab_Spec;
      Ada.Calendar'Elab_Body;
      E241 := E241 + 1;
      Ada.Calendar.Time_Zones'Elab_Spec;
      E247 := E247 + 1;
      Ada.Command_Line.Response_File'Elab_Spec;
      Gnat.Directory_Operations'Elab_Spec;
      System.Assertions'Elab_Spec;
      E145 := E145 + 1;
      System.Pool_Global'Elab_Spec;
      E207 := E207 + 1;
      E180 := E180 + 1;
      System.Finalization_Masters'Elab_Body;
      E174 := E174 + 1;
      E535 := E535 + 1;
      System.File_Io'Elab_Body;
      E070 := E070 + 1;
      E075 := E075 + 1;
      Ada.Tags'Elab_Body;
      E049 := E049 + 1;
      E094 := E094 + 1;
      System.Soft_Links'Elab_Body;
      E011 := E011 + 1;
      System.Os_Lib'Elab_Body;
      E077 := E077 + 1;
      System.Secondary_Stack'Elab_Body;
      E015 := E015 + 1;
      Gnat.Directory_Operations'Elab_Body;
      E087 := E087 + 1;
      E801 := E801 + 1;
      Ada.Strings.Unbounded'Elab_Spec;
      E201 := E201 + 1;
      Ada.Directories'Elab_Spec;
      Gnat.Expect'Elab_Spec;
      E530 := E530 + 1;
      System.Regexp'Elab_Spec;
      E212 := E212 + 1;
      Ada.Directories'Elab_Body;
      E239 := E239 + 1;
      E522 := E522 + 1;
      Gnat.Command_Line'Elab_Spec;
      Ada.Real_Time'Elab_Spec;
      Ada.Real_Time'Elab_Body;
      E492 := E492 + 1;
      Ada.Text_Io'Elab_Spec;
      Ada.Text_Io'Elab_Body;
      E062 := E062 + 1;
      Gnat.Command_Line'Elab_Body;
      E199 := E199 + 1;
      E462 := E462 + 1;
      Charset'Elab_Body;
      E131 := E131 + 1;
      Ocarina'Elab_Spec;
      E143 := E143 + 1;
      Errors'Elab_Spec;
      Ocarina.Analyzer.Aadl.Naming_Rules'Elab_Spec;
      Ocarina.Backends.Aadl_Xml'Elab_Spec;
      Ocarina.Backends.Ada_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Ada_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Ada_Values'Elab_Spec;
      Ocarina.Backends.Arinc653_Conf'Elab_Spec;
      Ocarina.Backends.Asn1'Elab_Spec;
      Ocarina.Backends.Asn1_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Asn1_Values'Elab_Spec;
      Ocarina.Backends.Asn1_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.C_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.C_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.C_Values'Elab_Spec;
      Ocarina.Backends.Cheddar'Elab_Spec;
      Ocarina.Backends.Connection_Matrix'Elab_Spec;
      Ocarina.Backends.Connection_Matrix.Main'Elab_Spec;
      Ocarina.Backends.Deos_Conf'Elab_Spec;
      Ocarina.Backends.Functions_Matrix'Elab_Spec;
      Ocarina.Backends.Functions_Matrix.Main'Elab_Spec;
      Ocarina.Backends.Mast'Elab_Spec;
      Ocarina.Backends.Mast_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Mast_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Mast_Values'Elab_Spec;
      Ocarina.Backends.Pn'Elab_Spec;
      Ocarina.Backends.Pn.Nodes'Elab_Spec;
      E666 := E666 + 1;
      E675 := E675 + 1;
      E668 := E668 + 1;
      Ocarina.Backends.Po_Hi_Ada'Elab_Spec;
      Ocarina.Backends.Pok_C'Elab_Spec;
      Ocarina.Backends.Pok_Cheddar'Elab_Spec;
      Ocarina.Backends.Execution_Tests'Elab_Spec;
      Ocarina.Backends.Execution_Utils'Elab_Spec;
      Ocarina.Backends.Lnt'Elab_Spec;
      Ocarina.Backends.Lnt.Nodes'Elab_Spec;
      Ocarina.Backends.Lnt.Nutils'Elab_Spec;
      E639 := E639 + 1;
      Ocarina.Backends.Stats'Elab_Spec;
      Ocarina.Backends.Stats.Main'Elab_Spec;
      Ocarina.Backends.Subprograms'Elab_Spec;
      Ocarina.Backends.Vxworks653_Conf'Elab_Spec;
      Ocarina.Backends.Xml_Tree.Nodes'Elab_Spec;
      Ocarina.Backends.Xml_Tree.Nutils'Elab_Spec;
      Ocarina.Backends.Xml_Values'Elab_Spec;
      Ocarina.Backends.Xtratum_Conf'Elab_Spec;
      Ocarina.Fe_Real.Parser'Elab_Spec;
      Ocarina.Files'Elab_Spec;
      E759 := E759 + 1;
      E611 := E611 + 1;
      E577 := E577 + 1;
      E571 := E571 + 1;
      E445 := E445 + 1;
      E380 := E380 + 1;
      Ocarina.Instances.Real_Checker.Queries'Elab_Spec;
      Ocarina.Me_Aadl.Aadl_Instances.Nodes'Elab_Spec;
      E431 := E431 + 1;
      E777 := E777 + 1;
      E555 := E555 + 1;
      Ocarina.Backends.Po_Hi_C.Request'Elab_Body;
      E569 := E569 + 1;
      E589 := E589 + 1;
      E585 := E585 + 1;
      E583 := E583 + 1;
      Ocarina.Backends.C_Common.Subprograms'Elab_Body;
      E480 := E480 + 1;
      E443 := E443 + 1;
      Ocarina.Backends.Arinc653_Conf.Partitions'Elab_Body;
      E439 := E439 + 1;
      E437 := E437 + 1;
      E435 := E435 + 1;
      E433 := E433 + 1;
      E426 := E426 + 1;
      E422 := E422 + 1;
      Ocarina.Me_Aadl.Aadl_Tree.Nodes'Elab_Spec;
      E705 := E705 + 1;
      E350 := E350 + 1;
      E348 := E348 + 1;
      E356 := E356 + 1;
      E340 := E340 + 1;
      Ocarina.Aadl_Values'Elab_Spec;
      E264 := E264 + 1;
      E352 := E352 + 1;
      E342 := E342 + 1;
      E359 := E359 + 1;
      E346 := E346 + 1;
      E344 := E344 + 1;
      E354 := E354 + 1;
      E336 := E336 + 1;
      E338 := E338 + 1;
      E271 := E271 + 1;
      E287 := E287 + 1;
      E285 := E285 + 1;
      E837 := E837 + 1;
      E283 := E283 + 1;
      E281 := E281 + 1;
      E279 := E279 + 1;
      E277 := E277 + 1;
      E829 := E829 + 1;
      E273 := E273 + 1;
      E813 := E813 + 1;
      E289 := E289 + 1;
      E258 := E258 + 1;
      Ocarina.Me_Aadl_Ba.Ba_Tree.Nodes'Elab_Spec;
      E896 := E896 + 1;
      E882 := E882 + 1;
      E890 := E890 + 1;
      E886 := E886 + 1;
      Ocarina.Me_Aadl_Ema.Ema_Tokens'Elab_Spec;
      E900 := E900 + 1;
      Ocarina.Me_Aadl_Ema.Ema_Tree.Nodes'Elab_Spec;
      E310 := E310 + 1;
      Ocarina.Ema_Values'Elab_Spec;
      Ocarina.Me_Aadl_Ema.Ema_Tree.Nutils'Elab_Spec;
      E304 := E304 + 1;
      Ocarina.Me_Ao4aadl.Ao4aadl_Tree.Nodes'Elab_Spec;
      Ocarina.Ao4aadl_Values'Elab_Spec;
      Ocarina.Me_Ao4aadl.Ao4aadl_Tree.Nutils'Elab_Spec;
      E918 := E918 + 1;
      Ocarina.Me_Ao4aadl.Tokens'Elab_Spec;
      Ocarina.Me_Real.Real_Tree.Nodes'Elab_Spec;
      Ocarina.Me_Real.Real_Tree.Nutils'Elab_Spec;
      Ocarina.Analyzer.Real.Finder'Elab_Spec;
      Ocarina.Me_Real.Tokens'Elab_Spec;
      E847 := E847 + 1;
      Ocarina.Namet'Elab_Spec;
      E926 := E926 + 1;
      Ocarina.Ao4aadl_Values'Elab_Body;
      E914 := E914 + 1;
      E317 := E317 + 1;
      Ocarina.Ema_Values'Elab_Body;
      E904 := E904 + 1;
      E235 := E235 + 1;
      E302 := E302 + 1;
      Ocarina.Aadl_Values'Elab_Body;
      E109 := E109 + 1;
      E364 := E364 + 1;
      E275 := E275 + 1;
      E795 := E795 + 1;
      E783 := E783 + 1;
      Ocarina.Backends.Xml_Values'Elab_Body;
      E391 := E391 + 1;
      E781 := E781 + 1;
      E779 := E779 + 1;
      E775 := E775 + 1;
      E771 := E771 + 1;
      E773 := E773 + 1;
      E769 := E769 + 1;
      E767 := E767 + 1;
      Ocarina.Backends.Utils'Elab_Body;
      E395 := E395 + 1;
      E797 := E797 + 1;
      E793 := E793 + 1;
      E791 := E791 + 1;
      Ocarina.Backends.Subprograms'Elab_Body;
      E765 := E765 + 1;
      E763 := E763 + 1;
      Ocarina.Backends.Stats.Main'Elab_Body;
      E761 := E761 + 1;
      Ocarina.Backends.Properties.Arinc653'Elab_Body;
      E609 := E609 + 1;
      E633 := E633 + 1;
      E524 := E524 + 1;
      E428 := E428 + 1;
      Ocarina.Backends.Pok_Cheddar'Elab_Body;
      E557 := E557 + 1;
      Ocarina.Backends.Pok_C.Main'Elab_Body;
      E551 := E551 + 1;
      E545 := E545 + 1;
      Ocarina.Backends.Po_Hi_C.Marshallers'Elab_Body;
      E565 := E565 + 1;
      Ocarina.Backends.Po_Hi_C.Main'Elab_Body;
      E563 := E563 + 1;
      Ocarina.Backends.Po_Hi_C.Activity'Elab_Body;
      E559 := E559 + 1;
      E699 := E699 + 1;
      E697 := E697 + 1;
      E695 := E695 + 1;
      Ocarina.Backends.Po_Hi_Ada.Runtime'Elab_Body;
      E685 := E685 + 1;
      E693 := E693 + 1;
      E691 := E691 + 1;
      E689 := E689 + 1;
      Ocarina.Backends.Po_Hi_Ada.Deployment'Elab_Body;
      E687 := E687 + 1;
      Ocarina.Backends.Po_Hi_Ada.Activity'Elab_Body;
      E681 := E681 + 1;
      Ocarina.Backends.Mast_Values'Elab_Body;
      E650 := E650 + 1;
      Ocarina.Backends.Mast_Tree.Nutils'Elab_Body;
      E652 := E652 + 1;
      E643 := E643 + 1;
      E641 := E641 + 1;
      Ocarina.Backends.Functions_Matrix.Main'Elab_Body;
      E613 := E613 + 1;
      E607 := E607 + 1;
      E581 := E581 + 1;
      Ocarina.Backends.Connection_Matrix.Main'Elab_Body;
      E579 := E579 + 1;
      E573 := E573 + 1;
      Ocarina.Backends.C_Values'Elab_Body;
      E476 := E476 + 1;
      Ocarina.Backends.C_Common.Types'Elab_Body;
      E484 := E484 + 1;
      Ocarina.Backends.Asn1_Tree.Nutils'Elab_Body;
      E454 := E454 + 1;
      Ocarina.Backends.Asn1_Values'Elab_Body;
      E456 := E456 + 1;
      Ocarina.Backends.Arinc653_Conf.Scheduling'Elab_Body;
      E441 := E441 + 1;
      E424 := E424 + 1;
      Ocarina.Backends.Alloy'Elab_Body;
      E420 := E420 + 1;
      Ocarina.Backends.Ada_Values'Elab_Body;
      E406 := E406 + 1;
      E384 := E384 + 1;
      E382 := E382 + 1;
      Ocarina.Annotations'Elab_Body;
      E159 := E159 + 1;
      E308 := E308 + 1;
      E223 := E223 + 1;
      Ocarina.Analyzer'Elab_Body;
      E215 := E215 + 1;
      E157 := E157 + 1;
      E107 := E107 + 1;
      Ocarina.Fe_Aadl_Ema.Lexer'Elab_Body;
      E906 := E906 + 1;
      Ocarina.Fe_Ao4aadl.Lexer'Elab_Body;
      E924 := E924 + 1;
      Ocarina.Fe_Real.Lexer'Elab_Spec;
      E851 := E851 + 1;
      Ocarina.Me_Aadl.Tokens'Elab_Spec;
      E755 := E755 + 1;
      E733 := E733 + 1;
      Ocarina.Fe_Aadl.Lexer'Elab_Spec;
      E803 := E803 + 1;
      E821 := E821 + 1;
      E835 := E835 + 1;
      E841 := E841 + 1;
      E839 := E839 + 1;
      E819 := E819 + 1;
      E833 := E833 + 1;
      E831 := E831 + 1;
      E817 := E817 + 1;
      E815 := E815 + 1;
      E825 := E825 + 1;
      E827 := E827 + 1;
      Ocarina.Me_Aadl_Ba.Tokens'Elab_Spec;
      E232 := E232 + 1;
      Ocarina.Fe_Aadl_Ba.Lexer'Elab_Spec;
      Ocarina.Fe_Aadl_Ba.Lexer'Elab_Body;
      E877 := E877 + 1;
      E892 := E892 + 1;
      E888 := E888 + 1;
      E884 := E884 + 1;
      E894 := E894 + 1;
      E879 := E879 + 1;
      Ocarina.Options'Elab_Spec;
      E253 := E253 + 1;
      E809 := E809 + 1;
      E237 := E237 + 1;
      Ocarina.Output'Elab_Body;
      E141 := E141 + 1;
      E898 := E898 + 1;
      E869 := E869 + 1;
      E861 := E861 + 1;
      E867 := E867 + 1;
      E865 := E865 + 1;
      E863 := E863 + 1;
      E845 := E845 + 1;
      Ocarina.Fe_Aadl.Lexer'Elab_Body;
      E807 := E807 + 1;
      E737 := E737 + 1;
      E735 := E735 + 1;
      E751 := E751 + 1;
      E749 := E749 + 1;
      E747 := E747 + 1;
      E731 := E731 + 1;
      E745 := E745 + 1;
      E743 := E743 + 1;
      E741 := E741 + 1;
      E739 := E739 + 1;
      E727 := E727 + 1;
      E729 := E729 + 1;
      Ocarina.Namet'Elab_Body;
      E135 := E135 + 1;
      E853 := E853 + 1;
      E928 := E928 + 1;
      E908 := E908 + 1;
      Ocarina.Backends.Execution_Tests'Elab_Body;
      E490 := E490 + 1;
      Ocarina.Backends.Pok_C.Makefile'Elab_Body;
      E553 := E553 + 1;
      E486 := E486 + 1;
      E478 := E478 + 1;
      E673 := E673 + 1;
      E656 := E656 + 1;
      E408 := E408 + 1;
      E654 := E654 + 1;
      Ocarina.Backends'Elab_Body;
      E378 := E378 + 1;
      E082 := E082 + 1;
      E910 := E910 + 1;
      E873 := E873 + 1;
      E398 := E398 + 1;
      E450 := E450 + 1;
      E467 := E467 + 1;
      E617 := E617 + 1;
      E646 := E646 + 1;
      E662 := E662 + 1;
      E664 := E664 + 1;
      E671 := E671 + 1;
      E658 := E658 + 1;
      E387 := E387 + 1;
      E193 := E193 + 1;
      E189 := E189 + 1;
      E627 := E627 + 1;
      E225 := E225 + 1;
      E153 := E153 + 1;
      E195 := E195 + 1;
      E362 := E362 + 1;
      E217 := E217 + 1;
      E859 := E859 + 1;
      E298 := E298 + 1;
      E313 := E313 + 1;
      E920 := E920 + 1;
      E326 := E326 + 1;
      E330 := E330 + 1;
      E328 := E328 + 1;
      E875 := E875 + 1;
      E811 := E811 + 1;
      Ocarina.Fe_Ao4aadl.Parser'Elab_Body;
      E912 := E912 + 1;
      Ocarina.Fe_Aadl_Ema.Parser'Elab_Body;
      E902 := E902 + 1;
      E262 := E262 + 1;
      E229 := E229 + 1;
      Ocarina.Parser'Elab_Body;
      E843 := E843 + 1;
      E823 := E823 + 1;
      E805 := E805 + 1;
      E753 := E753 + 1;
      E221 := E221 + 1;
      Ocarina.Real_Expander.Flow_Analysis'Elab_Body;
      E376 := E376 + 1;
      Ocarina.Real_Values'Elab_Spec;
      Ocarina.Real_Values'Elab_Body;
      E368 := E368 + 1;
      E374 := E374 + 1;
      E721 := E721 + 1;
      Ocarina.Fe_Real.Parser'Elab_Body;
      E849 := E849 + 1;
      E323 := E323 + 1;
      Ocarina.Analyzer.Real'Elab_Body;
      E319 := E319 + 1;
      E871 := E871 + 1;
      Ocarina.Transfo'Elab_Spec;
      Ocarina.Transfo.Fusions'Elab_Spec;
      E857 := E857 + 1;
      Ocarina.Transfo.Fusions.Scheduler'Elab_Spec;
      Ocarina.Transfo.Fusions.Scheduler'Elab_Body;
      E934 := E934 + 1;
      Ocarina.Transfo.Move'Elab_Body;
      E936 := E936 + 1;
      Ocarina.Transfo.Optim.Eval'Elab_Spec;
      Ocarina.Transfo.Optim.Eval'Elab_Body;
      E940 := E940 + 1;
      Ocarina.Transfo.Optim'Elab_Body;
      E938 := E938 + 1;
      E855 := E855 + 1;
      E293 := E293 + 1;
      E291 := E291 + 1;
      E625 := E625 + 1;
      E623 := E623 + 1;
      E458 := E458 + 1;
      Utils'Elab_Spec;
      E163 := E163 + 1;
      Ocarina.Utils'Elab_Body;
      E942 := E942 + 1;
      Ocarina.Transfo.Fusions'Elab_Body;
      E932 := E932 + 1;
      E930 := E930 + 1;
      E267 := E267 + 1;
      E922 := E922 + 1;
      E315 := E315 + 1;
      E300 := E300 + 1;
      E155 := E155 + 1;
      E191 := E191 + 1;
      E389 := E389 + 1;
      E660 := E660 + 1;
      E648 := E648 + 1;
      E619 := E619 + 1;
      E469 := E469 + 1;
      E452 := E452 + 1;
      E400 := E400 + 1;
      E725 := E725 + 1;
      E256 := E256 + 1;
      E321 := E321 + 1;
      Ocarina.Me_Real.Real_Tree.Nutils'Elab_Body;
      E332 := E332 + 1;
      E306 := E306 + 1;
      E197 := E197 + 1;
      E227 := E227 + 1;
      E366 := E366 + 1;
      Ocarina.Backends.Properties.Utils'Elab_Body;
      E414 := E414 + 1;
      E575 := E575 + 1;
      E187 := E187 + 1;
      E334 := E334 + 1;
      E789 := E789 + 1;
      E787 := E787 + 1;
      E785 := E785 + 1;
      Ocarina.Backends.Xml_Tree.Nutils'Elab_Body;
      E393 := E393 + 1;
      E418 := E418 + 1;
      E723 := E723 + 1;
      Ocarina.Backends.Replication_Properties'Elab_Body;
      E757 := E757 + 1;
      E683 := E683 + 1;
      E637 := E637 + 1;
      E635 := E635 + 1;
      E629 := E629 + 1;
      Ocarina.Backends.Lnt.Nutils'Elab_Body;
      E621 := E621 + 1;
      E631 := E631 + 1;
      E615 := E615 + 1;
      E587 := E587 + 1;
      E474 := E474 + 1;
      Ocarina.Backends.Build_Utils'Elab_Body;
      E464 := E464 + 1;
      Ocarina.Backends.Properties'Elab_Body;
      E412 := E412 + 1;
      Ocarina.Backends.Pok_C.Runtime'Elab_Body;
      E547 := E547 + 1;
      Ocarina.Backends.Pok_C.Deployment'Elab_Body;
      E549 := E549 + 1;
      Ocarina.Backends.Po_Hi_C.Runtime'Elab_Body;
      E482 := E482 + 1;
      Ocarina.Backends.Po_Hi_C.Naming'Elab_Body;
      E567 := E567 + 1;
      Ocarina.Backends.Po_Hi_C.Deployment'Elab_Body;
      E561 := E561 + 1;
      E677 := E677 + 1;
      E416 := E416 + 1;
      Ocarina.Backends.C_Tree.Nutils'Elab_Body;
      E471 := E471 + 1;
      E488 := E488 + 1;
      E460 := E460 + 1;
      Ocarina.Backends.Asn1.Deployment'Elab_Body;
      E447 := E447 + 1;
      Ocarina.Backends.Ada_Tree.Nutils'Elab_Body;
      E402 := E402 + 1;
      E679 := E679 + 1;
      E295 := E295 + 1;
      E260 := E260 + 1;
      E219 := E219 + 1;
      E799 := E799 + 1;
      E703 := E703 + 1;
      E707 := E707 + 1;
      E709 := E709 + 1;
      E711 := E711 + 1;
      E713 := E713 + 1;
      E715 := E715 + 1;
      E717 := E717 + 1;
      E719 := E719 + 1;
      Ocarina.Backends.Real'Elab_Body;
      E701 := E701 + 1;
   end adainit;

   procedure Ada_Main_Program;
   pragma Import (Ada, Ada_Main_Program, "_ada_ocarina_cmd");

   function main
     (argc : Integer;
      argv : System.Address;
      envp : System.Address)
      return Integer
   is
      procedure Initialize (Addr : System.Address);
      pragma Import (C, Initialize, "__gnat_initialize");

      procedure Finalize;
      pragma Import (C, Finalize, "__gnat_finalize");
      SEH : aliased array (1 .. 2) of Integer;

      Ensure_Reference : aliased System.Address := Ada_Main_Program_Name'Address;
      pragma Volatile (Ensure_Reference);

   begin
      gnat_argc := argc;
      gnat_argv := argv;
      gnat_envp := envp;

      Initialize (SEH'Address);
      adainit;
      Ada_Main_Program;
      adafinal;
      Finalize;
      return (gnat_exit_status);
   end;

--  BEGIN Object file/option list
   --   /home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/ocarina_cmd.o
   --   /home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/ocarina-scripts.o
   --   /home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/ocarina-utils.o
   --   /home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/ocarina-cmd_line.o
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/main/objects/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/core/libs/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/config/libs/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/frontends/libs/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/backends/libs/
   --   -L/home/francis/polyorb-hi-c/ocarina-build/ocarina/src/transfo/libs/
   --   -L/usr/lib/gcc/i686-linux-gnu/6/adalib/
   --   -static
   --   -lgnarl
   --   -lgnat
   --   -lpthread
   --   -lrt
--  END Object file/option list   

end ada_main;
