#ifndef _INC_IP_H
#define _INC_IP_H
/*
Code automatically generated by asn1scc tool
Date was: 2/7/2012
Time was: 15:35:34
*/

#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef asn1SccSint __po_hi_c_Port_T;

#define __po_hi_c_Port_T_REQUIRED_BYTES_FOR_ENCODING        2
#define __po_hi_c_Port_T_REQUIRED_BITS_FOR_ENCODING        15
#define __po_hi_c_Port_T_REQUIRED_BYTES_FOR_ACN_ENCODING       2
#define __po_hi_c_Port_T_REQUIRED_BITS_FOR_ACN_ENCODING        15
#define __po_hi_c_Port_T_REQUIRED_BYTES_FOR_XER_ENCODING       37

#ifndef ERR___po_hi_c_Port_T 
#define ERR___po_hi_c_Port_T		1000 /* (0..16535) */
#endif

void __po_hi_c_Port_T_Initialize(__po_hi_c_Port_T* pVal);
flag __po_hi_c_Port_T_IsConstraintValid(const __po_hi_c_Port_T* val, int* pErrCode);


typedef enum {
    __po_hi_c_ipv4 = 0,
    __po_hi_c_ipv6 = 1
} __po_hi_c_Version_T;

#define __po_hi_c_Version_T_REQUIRED_BYTES_FOR_ENCODING        1
#define __po_hi_c_Version_T_REQUIRED_BITS_FOR_ENCODING        1
#define __po_hi_c_Version_T_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define __po_hi_c_Version_T_REQUIRED_BITS_FOR_ACN_ENCODING        1
#define __po_hi_c_Version_T_REQUIRED_BYTES_FOR_XER_ENCODING       34

#ifndef ERR___po_hi_c_Version_T_unknown_enumeration_value 
#define ERR___po_hi_c_Version_T_unknown_enumeration_value		1001 /* invalid enumeration value */
#endif

void __po_hi_c_Version_T_Initialize(__po_hi_c_Version_T* pVal);
flag __po_hi_c_Version_T_IsConstraintValid(const __po_hi_c_Version_T* val, int* pErrCode);


typedef struct {
    char devname[21];
    char address[41];
    char broadcast[41];
    char netmask[41];
    char gateway[41];
    char dns[41];
    __po_hi_c_Version_T version;
    __po_hi_c_Port_T port;
    struct {
        unsigned int broadcast:1;
        unsigned int netmask:1;
        unsigned int gateway:1;
        unsigned int dns:1;
        unsigned int version:1;
    } exist;
} __po_hi_c_ip_conf_t;

#define __po_hi_c_ip_conf_t_REQUIRED_BYTES_FOR_ENCODING        200
#define __po_hi_c_ip_conf_t_REQUIRED_BITS_FOR_ENCODING        1596
#define __po_hi_c_ip_conf_t_REQUIRED_BYTES_FOR_ACN_ENCODING       227
#define __po_hi_c_ip_conf_t_REQUIRED_BITS_FOR_ACN_ENCODING        1816
#define __po_hi_c_ip_conf_t_REQUIRED_BYTES_FOR_XER_ENCODING       416

#ifndef ERR___po_hi_c_ip_conf_t_devname 
#define ERR___po_hi_c_ip_conf_t_devname		1002 /* (SIZE (1..20)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_address 
#define ERR___po_hi_c_ip_conf_t_address		1003 /* (SIZE (1..40)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_broadcast 
#define ERR___po_hi_c_ip_conf_t_broadcast		1004 /* (SIZE (1..40)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_netmask 
#define ERR___po_hi_c_ip_conf_t_netmask		1005 /* (SIZE (1..40)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_gateway 
#define ERR___po_hi_c_ip_conf_t_gateway		1006 /* (SIZE (1..40)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_dns 
#define ERR___po_hi_c_ip_conf_t_dns		1007 /* (SIZE (1..40)) */
#endif

void __po_hi_c_ip_conf_t_Initialize(__po_hi_c_ip_conf_t* pVal);
flag __po_hi_c_ip_conf_t_IsConstraintValid(const __po_hi_c_ip_conf_t* val, int* pErrCode);


extern  __po_hi_c_ip_conf_t localhost1;
extern  __po_hi_c_ip_conf_t localhost2;

#ifdef  __cplusplus
}
#define ENUM___po_hi_c_ipv4	__po_hi_c_ipv4
#define ENUM___po_hi_c_ipv6	__po_hi_c_ipv6
#endif

#endif
