#ifndef _INC_IP_H
#define _INC_IP_H
/*
Code automatically generated by asn1scc tool
Date was: 6/21/2011
Time was: 18:14:47
*/

#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef asn1SccSint __po_hi_c_Port_T;

#define __po_hi_c_Port_T_REQUIRED_BYTES_FOR_ENCODING        2
#define __po_hi_c_Port_T_REQUIRED_BITS_FOR_ENCODING        15
#define __po_hi_c_Port_T_REQUIRED_BYTES_FOR_ACN_ENCODING       2
#define __po_hi_c_Port_T_REQUIRED_BITS_FOR_ACN_ENCODING        15

#ifndef ERR___po_hi_c_Port_T 
#define ERR___po_hi_c_Port_T		1000 /* (0..16535) */
#endif

void __po_hi_c_Port_T_Initialize(__po_hi_c_Port_T* pVal);
flag __po_hi_c_Port_T_IsConstraintValid(const __po_hi_c_Port_T* val, int* pErrCode);


typedef enum {
    __po_hi_c_ipv4 = 0,
    __po_hi_c_ipv6 = 1
} __po_hi_c_Version_T;

#define __po_hi_c_Version_T_REQUIRED_BYTES_FOR_ENCODING        1
#define __po_hi_c_Version_T_REQUIRED_BITS_FOR_ENCODING        1
#define __po_hi_c_Version_T_REQUIRED_BYTES_FOR_ACN_ENCODING       1
#define __po_hi_c_Version_T_REQUIRED_BITS_FOR_ACN_ENCODING        1

#ifndef ERR___po_hi_c_Version_T_unknown_enumeration_value 
#define ERR___po_hi_c_Version_T_unknown_enumeration_value		1001 /* invalid enumeration value */
#endif

void __po_hi_c_Version_T_Initialize(__po_hi_c_Version_T* pVal);
flag __po_hi_c_Version_T_IsConstraintValid(const __po_hi_c_Version_T* val, int* pErrCode);


typedef struct {
    char devname[21];
    char address[41];
    __po_hi_c_Version_T version;
    __po_hi_c_Port_T port;
    struct {
        unsigned int version:1;
    } exist;
} __po_hi_c_ip_conf_t;

#define __po_hi_c_ip_conf_t_REQUIRED_BYTES_FOR_ENCODING        56
#define __po_hi_c_ip_conf_t_REQUIRED_BITS_FOR_ENCODING        448
#define __po_hi_c_ip_conf_t_REQUIRED_BYTES_FOR_ACN_ENCODING       64
#define __po_hi_c_ip_conf_t_REQUIRED_BITS_FOR_ACN_ENCODING        508

#ifndef ERR___po_hi_c_ip_conf_t_devname 
#define ERR___po_hi_c_ip_conf_t_devname		1002 /* (SIZE (1..20)) */
#endif
#ifndef ERR___po_hi_c_ip_conf_t_address 
#define ERR___po_hi_c_ip_conf_t_address		1003 /* (SIZE (1..40)) */
#endif

void __po_hi_c_ip_conf_t_Initialize(__po_hi_c_ip_conf_t* pVal);
flag __po_hi_c_ip_conf_t_IsConstraintValid(const __po_hi_c_ip_conf_t* val, int* pErrCode);


extern  __po_hi_c_ip_conf_t localhost1;
extern  __po_hi_c_ip_conf_t localhost2;

#ifdef  __cplusplus
}
#define ENUM___po_hi_c_ipv4	__po_hi_c_ipv4
#define ENUM___po_hi_c_ipv6	__po_hi_c_ipv6
#endif

#endif
