#if (defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX) || defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX_RECEIVER) || defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX_SENDER) || defined (__PO_HI_NEED_DRIVER_SERIAL_RASTA) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON_SENDER) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON_RECEIVER))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "serial.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Baudrate_T_Initialize(__po_hi_c_Baudrate_T* pVal)
{
    *pVal = (__po_hi_c_Baudrate_T) __po_hi_c_b9600;
}
#endif

 
flag __po_hi_c_Baudrate_T_IsConstraintValid(const __po_hi_c_Baudrate_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((((((*pVal == __po_hi_c_b9600) || (*pVal == __po_hi_c_b19200)) || (*pVal == __po_hi_c_b38400)) || (*pVal == __po_hi_c_b57600)) || (*pVal == __po_hi_c_b115200)) || (*pVal == __po_hi_c_b230400));
	*pErrCode = ret ? 0 : ERR___po_hi_c_Baudrate_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Parity_T_Initialize(__po_hi_c_Parity_T* pVal)
{
    *pVal = (__po_hi_c_Parity_T) __po_hi_c_even;
}
#endif

 
flag __po_hi_c_Parity_T_IsConstraintValid(const __po_hi_c_Parity_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((*pVal == __po_hi_c_even) || (*pVal == __po_hi_c_odd));
	*pErrCode = ret ? 0 : ERR___po_hi_c_Parity_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_serial_conf_t_sending_wait_Initialize(__po_hi_c_serial_conf_t_sending_wait* pVal)
{
    *pVal = (__po_hi_c_serial_conf_t_sending_wait) 0;
}
#endif

 
flag __po_hi_c_serial_conf_t_sending_wait_IsConstraintValid(const __po_hi_c_serial_conf_t_sending_wait* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= *pVal && *pVal <= 9000000);
	*pErrCode = ret ? 0 : ERR___po_hi_c_serial_conf_t_sending_wait;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_serial_conf_t_bits_Initialize(__po_hi_c_serial_conf_t_bits* pVal)
{
    *pVal = (__po_hi_c_serial_conf_t_bits) 7;
}
#endif

 
flag __po_hi_c_serial_conf_t_bits_IsConstraintValid(const __po_hi_c_serial_conf_t_bits* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (7 <= *pVal && *pVal <= 8);
	*pErrCode = ret ? 0 : ERR___po_hi_c_serial_conf_t_bits;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_serial_conf_t_devname_Initialize(__po_hi_c_serial_conf_t_devname pVal)
{
    static __po_hi_c_serial_conf_t_devname ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag __po_hi_c_serial_conf_t_devname_IsConstraintValid(const __po_hi_c_serial_conf_t_devname pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 20);
	*pErrCode = ret ? 0 : ERR___po_hi_c_serial_conf_t_devname;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_serial_conf_t_Initialize(__po_hi_c_serial_conf_t* pVal)
{
    *pVal = (__po_hi_c_serial_conf_t) {
    .devname = " ",
    .speed = __po_hi_c_b9600,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 1,
        .bits = 1,
        .sending_wait = 1,
        .use_paritybit = 1
    }
};
}
#endif

 
flag __po_hi_c_serial_conf_t_IsConstraintValid(const __po_hi_c_serial_conf_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = __po_hi_c_serial_conf_t_devname_IsConstraintValid(pVal->devname, pErrCode);
	if (ret) {
	    if (pVal->exist.speed==1) {
	        ret = __po_hi_c_Baudrate_T_IsConstraintValid(&pVal->speed, pErrCode);
	    }
	    if (ret) {
	        if (pVal->exist.parity==1) {
	            ret = __po_hi_c_Parity_T_IsConstraintValid(&pVal->parity, pErrCode);
	        }
	        if (ret) {
	            if (pVal->exist.bits==1) {
	                ret = __po_hi_c_serial_conf_t_bits_IsConstraintValid(&pVal->bits, pErrCode);
	            }
	            if (ret) {
	                if (pVal->exist.sending_wait==1) {
	                    ret = __po_hi_c_serial_conf_t_sending_wait_IsConstraintValid(&pVal->sending_wait, pErrCode);
	                }
	                if (ret) {
	                    if (pVal->exist.use_paritybit==1) {
	                        ret = TRUE; *pErrCode = 0;
	                    }
	                
	                }
	            }
	        }
	    }
	}

	return ret;
}

const __po_hi_c_serial_conf_t linux_ttyS0 = {
    .devname = "/dev/ttyS0",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};

const __po_hi_c_serial_conf_t linux_ttyUSB0 = {
    .devname = "/dev/ttyUSB0",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};

const __po_hi_c_serial_conf_t linux_ttyUSB1 = {
    .devname = "/dev/ttyUSB1",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};

const __po_hi_c_serial_conf_t linux_ttyUSB2 = {
    .devname = "/dev/ttyUSB2",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};

const __po_hi_c_serial_conf_t leon_rasta_apburasta0 = {
    .devname = "/dev/apburasta0",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};

const __po_hi_c_serial_conf_t leon_rasta_apburasta1 = {
    .devname = "/dev/apburasta1",
    .speed = __po_hi_c_b38400,
    .parity = __po_hi_c_even,
    .bits = 7,
    .sending_wait = 0,
    .use_paritybit = FALSE,
    .exist = {
        .speed = 1,
        .parity = 0,
        .bits = 0,
        .sending_wait = 0,
        .use_paritybit = 0
    }
};
\n#endif
