#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/

/*!
 * \fn __PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
 * \brief Main function executed by the system
 *
 * Full function name and return types are available  in the PolyORB-HI-C 
 * runtime header files.
 */
__PO_HI_MAIN_TYPE __PO_HI_MAIN_NAME (void)
{
  
/*!
 * \var period
 * \brief Variable for task period
 *
 * This variable is used to store the valueof the period of a task when we 
 * create it. The value put in the variable is set according to AADL model 
 * description
 */
  __po_hi_time_t period;

  __po_hi_initialize_early ();
  
/*!
 * Initialize the runtime
 */
  __po_hi_initialize ();
  
/*!
 * Store the period time for task pinger
 */
  __po_hi_milliseconds (&(period), 500);
  
/*!
 * \brief Making Periodic Task pinger
 *
 * Make a periodic task according to AADL model requirements. The first 
 * parameter is the task identifier defined in deployment.h 
 * (node_a_pinger_k) the second is the period defined in the AADL model. 
 * Third is the task priority ( 2), fourth is the stack size ( 0 bytes) and 
 * last is the subprogram executed by the task
 */
  __po_hi_create_periodic_task (node_a_pinger_k, &(period), 2, 0, 0, pinger_job);
  
/*!
 * Store the period time for task ping_me
 */
  __po_hi_milliseconds (&(period), 10);
  
/*!
 * Making Sporadic task
 */
  __po_hi_create_sporadic_task (node_a_ping_me_k, &(period), 1, 0, 0, ping_me_job);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  
/*!
 * Used to switch the main task to sleep all the time
 */
  __po_hi_wait_for_tasks ();
  
/*!
 * Return Statement
 */
  return (__PO_HI_MAIN_RETURN);
}


