#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_simple_type 
    (software__simple_type value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (&(value), message, 8, offset);
}

void __po_hi_unmarshall_type_simple_type 
    (software__simple_type* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 8, offset);
}

void __po_hi_marshall_request_pinger_data_source 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_simple_type (request->vars.pinger_global_data_source.pinger_global_data_source, message, offset);
}

void __po_hi_unmarshall_request_pinger_data_source 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_simple_type (&(request->vars.pinger_global_data_source.pinger_global_data_source), message, offset);
}

void __po_hi_marshall_request_ping_me_data_sink 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_simple_type (request->vars.ping_me_global_data_sink.ping_me_global_data_sink, message, offset);
}

void __po_hi_unmarshall_request_ping_me_data_sink 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_simple_type (&(request->vars.ping_me_global_data_sink.ping_me_global_data_sink), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case pinger_global_data_source:
    {
      __po_hi_marshall_request_pinger_data_source (request, message, &(offset));

      break;
    }
    case ping_me_global_data_sink:
    {
      __po_hi_marshall_request_ping_me_data_sink (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case pinger_global_data_source:
    {
      __po_hi_unmarshall_request_pinger_data_source (request, message, &(offset));

      break;
    }
    case ping_me_global_data_sink:
    {
      __po_hi_unmarshall_request_ping_me_data_sink (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


