#include <deployment.h>
#include <po_hi_types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
const char* __po_hi_ports_names[__PO_HI_NB_PORTS] = {"pinger_global_data_source","ping_me_global_data_sink"};

