#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void user_do_ping_spg 
    (software__simple_type* data_source);
void software__do_ping_spg 
    (software__simple_type* data_source)
{

  user_do_ping_spg (data_source);
}

void user_ping_spg 
    (software__simple_type data_sink);
void software__ping_spg 
    (software__simple_type data_sink)
{

  user_ping_spg (data_sink);
}


