#ifndef __OCARINA_GENERATED_TYPES_H_
#define __OCARINA_GENERATED_TYPES_H_ 
#include <po_hi_types.h>
#include <ping.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

typedef custom_int software__simple_type;

#endif
