#include <deployment.h>
#include <po_hi_gqueue.h>
#include <po_hi_types.h>
#include <request.h>
#include <types.h>
#include "subprograms.h"
#include <activity.h>
#include <po_hi_task.h>
#include <po_hi_main.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
__po_hi_port_t __po_hi_producer_data_source_local_destinations[1] = {consumer_global_data_sink};
__po_hi_port_id_t __po_hi_producer_woffsets[__po_hi_producer_nb_ports];
__po_hi_port_id_t __po_hi_producer_offsets[__po_hi_producer_nb_ports];
__po_hi_port_id_t __po_hi_producer_used_size[__po_hi_producer_nb_ports];
__po_hi_port_id_t __po_hi_producer_empties[__po_hi_producer_nb_ports];
__po_hi_port_id_t __po_hi_producer_first[__po_hi_producer_nb_ports];
__po_hi_request_t __po_hi_producer_recent[__po_hi_producer_nb_ports];
__po_hi_port_t __po_hi_producer_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_producer_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_producer_history[0];
__po_hi_port_id_t __po_hi_producer_n_dest[__po_hi_producer_nb_ports] = {1};
__po_hi_port_id_t __po_hi_producer_fifo_size[__po_hi_producer_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_producer_destinations[__po_hi_producer_nb_ports] = {__po_hi_producer_data_source_local_destinations};

/*!
 * \fn void* producer_job (void)
 * \brief Function executed by the task producer
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Producer*/
void* producer_job (void)
{
  static software__alpha_type data_source_request_var;
  static __po_hi_request_t data_source_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (pr_a_producer_k, __po_hi_producer_nb_ports, __po_hi_producer_queue, __po_hi_producer_fifo_size, __po_hi_producer_first, __po_hi_producer_offsets, __po_hi_producer_woffsets, __po_hi_producer_n_dest, __po_hi_producer_destinations, __po_hi_producer_used_size, __po_hi_producer_history, __po_hi_producer_recent, __po_hi_producer_empties, __po_hi_producer_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (pr_a_producer_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (pr_a_producer_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Call implementation*/
    software__produce_spg (&(data_source_request_var));
    /*  Set the OUT port values*/
    data_source_request.vars.producer_global_data_source.producer_global_data_source = data_source_request_var;
    data_source_request.port = producer_global_data_source;
    __po_hi_gqueue_store_out (pr_a_producer_k, producer_local_data_source, &(data_source_request));
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (pr_a_producer_k, producer_global_data_source);
    __po_hi_wait_for_next_period (pr_a_producer_k);
  }
}

__po_hi_port_id_t __po_hi_result_consumer_woffsets[__po_hi_result_consumer_nb_ports];
__po_hi_port_id_t __po_hi_result_consumer_offsets[__po_hi_result_consumer_nb_ports];
__po_hi_port_id_t __po_hi_result_consumer_used_size[__po_hi_result_consumer_nb_ports];
__po_hi_port_id_t __po_hi_result_consumer_empties[__po_hi_result_consumer_nb_ports];
__po_hi_port_id_t __po_hi_result_consumer_first[__po_hi_result_consumer_nb_ports];
__po_hi_request_t __po_hi_result_consumer_recent[__po_hi_result_consumer_nb_ports];
__po_hi_port_t __po_hi_result_consumer_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_result_consumer_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_result_consumer_history[0];
__po_hi_port_id_t __po_hi_result_consumer_n_dest[__po_hi_result_consumer_nb_ports] = {0};
__po_hi_port_id_t __po_hi_result_consumer_fifo_size[__po_hi_result_consumer_nb_ports] = {__PO_HI_GQUEUE_FIFO_INDATA};
__po_hi_port_t* __po_hi_result_consumer_destinations[__po_hi_result_consumer_nb_ports] = {NULL};

/*!
 * \fn void result_consumer_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task result_consumer
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (result_consumer_deliver) stores the incoming request for the 
 * taskresult_consumer
 */
void result_consumer_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case result_consumer_global_data_sink:
    {
      __po_hi_gqueue_store_in (pr_a_result_consumer_k, result_consumer_local_data_sink, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* result_consumer_job (void)
 * \brief Function executed by the task result_consumer
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : Result_Consumer*/
/*  Get the IN ports values*/
void* result_consumer_job (void)
{
  static __po_hi_request_t data_sink_request;

  __po_hi_gqueue_init (pr_a_result_consumer_k, __po_hi_result_consumer_nb_ports, __po_hi_result_consumer_queue, __po_hi_result_consumer_fifo_size, __po_hi_result_consumer_first, __po_hi_result_consumer_offsets, __po_hi_result_consumer_woffsets, __po_hi_result_consumer_n_dest, __po_hi_result_consumer_destinations, __po_hi_result_consumer_used_size, __po_hi_result_consumer_history, __po_hi_result_consumer_recent, __po_hi_result_consumer_empties, __po_hi_result_consumer_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (pr_a_result_consumer_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (pr_a_result_consumer_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (pr_a_result_consumer_k, result_consumer_local_data_sink))
    {
          __po_hi_gqueue_get_value (pr_a_result_consumer_k, result_consumer_local_data_sink, &(data_sink_request));
      __po_hi_gqueue_next_value (pr_a_result_consumer_k, result_consumer_local_data_sink);

    }
    /*  Call implementation*/
    software__consume_spg (data_sink_request.vars.result_consumer_global_data_sink.result_consumer_global_data_sink);
    __po_hi_wait_for_next_period (pr_a_result_consumer_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case pr_a_result_consumer_k_entity:
    {
      result_consumer_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


