#ifndef __OCARINA_GENERATED_SUBPROGRAMS_H_
#define __OCARINA_GENERATED_SUBPROGRAMS_H_ 
#include <types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void software__produce_spg 
    (software__alpha_type* data_source);

void software__consume_spg 
    (software__alpha_type data_sink);

void ocarina_drivers_ip_pohic__spg_eth_linux_sender_i 
    (__po_hi_device_id dev_id);

#endif
