#if (defined (__PO_HI_NEED_DRIVER_1553_RASTA))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "1553.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Node_Addr_T_Initialize(__po_hi_c_Node_Addr_T* pVal)
{
    *pVal = (__po_hi_c_Node_Addr_T) 0;
}
#endif

 
flag __po_hi_c_Node_Addr_T_IsConstraintValid(const __po_hi_c_Node_Addr_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= *pVal && *pVal <= 31);
	*pErrCode = ret ? 0 : ERR___po_hi_c_Node_Addr_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Standard_T_Initialize(__po_hi_c_Standard_T* pVal)
{
    *pVal = (__po_hi_c_Standard_T) __po_hi_c_mil1553a;
}
#endif

 
flag __po_hi_c_Standard_T_IsConstraintValid(const __po_hi_c_Standard_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((*pVal == __po_hi_c_mil1553a) || (*pVal == __po_hi_c_mil1553b));
	*pErrCode = ret ? 0 : ERR___po_hi_c_Standard_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Mode_T_Initialize(__po_hi_c_Mode_T* pVal)
{
    *pVal = (__po_hi_c_Mode_T) __po_hi_c_controller;
}
#endif

 
flag __po_hi_c_Mode_T_IsConstraintValid(const __po_hi_c_Mode_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (((*pVal == __po_hi_c_controller) || (*pVal == __po_hi_c_terminal)) || (*pVal == __po_hi_c_monitor));
	*pErrCode = ret ? 0 : ERR___po_hi_c_Mode_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Bus_T_Initialize(__po_hi_c_Bus_T* pVal)
{
    *pVal = (__po_hi_c_Bus_T) __po_hi_c_none;
}
#endif

 
flag __po_hi_c_Bus_T_IsConstraintValid(const __po_hi_c_Bus_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((((*pVal == __po_hi_c_none) || (*pVal == __po_hi_c_bus_a)) || (*pVal == __po_hi_c_bus_b)) || (*pVal == __po_hi_c_both));
	*pErrCode = ret ? 0 : ERR___po_hi_c_Bus_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_mil_1553_conf_t_devname_Initialize(__po_hi_c_mil_1553_conf_t_devname pVal)
{
    static __po_hi_c_mil_1553_conf_t_devname ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag __po_hi_c_mil_1553_conf_t_devname_IsConstraintValid(const __po_hi_c_mil_1553_conf_t_devname pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 20);
	*pErrCode = ret ? 0 : ERR___po_hi_c_mil_1553_conf_t_devname;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_mil_1553_conf_t_Initialize(__po_hi_c_mil_1553_conf_t* pVal)
{
    *pVal = (__po_hi_c_mil_1553_conf_t) {
    .devname = " ",
    .standard = __po_hi_c_mil1553a,
    .mode = __po_hi_c_controller,
    .bus = __po_hi_c_none,
    .termaddr = 0,
    .broadcast = FALSE,
    .rxblock = FALSE,
    .txblock = FALSE,
    .exist = {
        .rxblock = 1,
        .txblock = 1
    }
};
}
#endif

 
flag __po_hi_c_mil_1553_conf_t_IsConstraintValid(const __po_hi_c_mil_1553_conf_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = __po_hi_c_mil_1553_conf_t_devname_IsConstraintValid(pVal->devname, pErrCode);
	if (ret) {
	    ret = __po_hi_c_Standard_T_IsConstraintValid(&pVal->standard, pErrCode);
	    if (ret) {
	        ret = __po_hi_c_Mode_T_IsConstraintValid(&pVal->mode, pErrCode);
	        if (ret) {
	            ret = __po_hi_c_Bus_T_IsConstraintValid(&pVal->bus, pErrCode);
	            if (ret) {
	                ret = __po_hi_c_Node_Addr_T_IsConstraintValid(&pVal->termaddr, pErrCode);
	                if (ret) {
	                    ret = TRUE; *pErrCode = 0;
	                    if (ret) {
	                        if (pVal->exist.rxblock==1) {
	                            ret = TRUE; *pErrCode = 0;
	                        }
	                        if (ret) {
	                            if (pVal->exist.txblock==1) {
	                                ret = TRUE; *pErrCode = 0;
	                            }
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

\n#endif
