POHICDRIVER-IP DEFINITIONS AUTOMATIC TAGS ::= BEGIN


Ip-Address-T ::= SEQUENCE (SIZE (4)) OF INTEGER (0 .. 255)

Port-T ::= INTEGER (0 .. 16535)

IP-Conf-T ::= SEQUENCE {
   devname        IA5String (SIZE (1..20)),
   address        Ip-Address-T,
   port           Port-T
}

END

