#if (defined (__PO_HI_NEED_DRIVER_SOCKETS) || defined (__PO_HI_NEED_DRIVER_RTEMS_NE2000_SOCKETS))\n
/*
Code automatically generated by asn1scc tool
Date was: 10/07/2011
Time was: 11:19:22
*/
#include <string.h>
#include <math.h>
#include "ip.h"


#ifndef _MSC_VER
__po_hi_c_ip_conf_t localhost1 = {
	.devname = "eth0",
	.address = "127.0.0.1",
	.port = 5489
}; 
__po_hi_c_ip_conf_t localhost2 = {
	.devname = "eth0",
	.address = "127.0.0.1",
	.port = 5489
}; 
#endif

void __po_hi_c_Port_T_Initialize(__po_hi_c_Port_T* pVal)
{
	*pVal = 0;
}


flag __po_hi_c_Port_T_IsConstraintValid(const __po_hi_c_Port_T* pVal, int* pErrCode) 
{
	if ( !(((*pVal>=0) && (*pVal<=16535))) ) {
		*pErrCode = ERR___po_hi_c_Port_T;
		return FALSE;
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}




void __po_hi_c_Version_T_Initialize(__po_hi_c_Version_T* pVal)
{
	*pVal = __po_hi_c_ipv4;
}


flag __po_hi_c_Version_T_IsConstraintValid(const __po_hi_c_Version_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}




void __po_hi_c_ip_conf_t_Initialize(__po_hi_c_ip_conf_t* pVal)
{
	memset(pVal->devname, 0x0, 21);
	memset(pVal->address, 0x0, 41);
	memset(pVal->broadcast, 0x0, 41);
	memset(pVal->netmask, 0x0, 41);
	memset(pVal->gateway, 0x0, 41);
	memset(pVal->dns, 0x0, 41);
	pVal->version = __po_hi_c_ipv4;
	pVal->port = 0;
}


flag __po_hi_c_ip_conf_t_IsConstraintValid(const __po_hi_c_ip_conf_t* pVal, int* pErrCode) 
{
	if ( !(((strlen(pVal->devname)>=1) && (strlen(pVal->devname)<=20))) ) {
		*pErrCode = ERR___po_hi_c_ip_conf_t_devname;
		return FALSE;
	}
	if ( !(((strlen(pVal->address)>=1) && (strlen(pVal->address)<=40))) ) {
		*pErrCode = ERR___po_hi_c_ip_conf_t_address;
		return FALSE;
	}
	if (pVal->exist.broadcast) {
		if ( !(((strlen(pVal->broadcast)>=1) && (strlen(pVal->broadcast)<=40))) ) {
			*pErrCode = ERR___po_hi_c_ip_conf_t_broadcast;
			return FALSE;
		}
	}
	if (pVal->exist.netmask) {
		if ( !(((strlen(pVal->netmask)>=1) && (strlen(pVal->netmask)<=40))) ) {
			*pErrCode = ERR___po_hi_c_ip_conf_t_netmask;
			return FALSE;
		}
	}
	if (pVal->exist.gateway) {
		if ( !(((strlen(pVal->gateway)>=1) && (strlen(pVal->gateway)<=40))) ) {
			*pErrCode = ERR___po_hi_c_ip_conf_t_gateway;
			return FALSE;
		}
	}
	if (pVal->exist.dns) {
		if ( !(((strlen(pVal->dns)>=1) && (strlen(pVal->dns)<=40))) ) {
			*pErrCode = ERR___po_hi_c_ip_conf_t_dns;
			return FALSE;
		}
	}
	if (pVal->exist.version) {
		if ( !__po_hi_c_Version_T_IsConstraintValid(&pVal->version, pErrCode)) 
			return FALSE;

	}
	if ( !__po_hi_c_Port_T_IsConstraintValid(&pVal->port, pErrCode)) 
		return FALSE;

	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}





\n#endif
