/*
Code automatically generated by asn1scc tool
Date was: 1/24/2011
Time was: 20:29:05
*/
#include <string.h>
#include <math.h>
#include "ip.h"


#ifndef _MSC_VER
#endif

void __po_hi_c_Port_T_Initialize(__po_hi_c_Port_T* pVal)
{
	*pVal = 0;
}


flag __po_hi_c_Port_T_IsConstraintValid(const __po_hi_c_Port_T* pVal, int* pErrCode) 
{
	if ( !(((*pVal>=0) && (*pVal<=16535))) ) {
		*pErrCode = ERR___po_hi_c_Port_T;
		return FALSE;
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Port_T_Equal(const __po_hi_c_Port_T* pVal1, const __po_hi_c_Port_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_Version_T_Initialize(__po_hi_c_Version_T* pVal)
{
	*pVal = __po_hi_c_ipv4;
}


flag __po_hi_c_Version_T_IsConstraintValid(const __po_hi_c_Version_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Version_T_Equal(const __po_hi_c_Version_T* pVal1, const __po_hi_c_Version_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_ip_conf_t_Initialize(__po_hi_c_ip_conf_t* pVal)
{
	memset(pVal->devname, 0x0, 21);
	memset(pVal->address, 0x0, 41);
	pVal->version = __po_hi_c_ipv4;
	pVal->port = 0;
}


flag __po_hi_c_ip_conf_t_IsConstraintValid(const __po_hi_c_ip_conf_t* pVal, int* pErrCode) 
{
	if ( !(((strlen(pVal->devname)>=1) && (strlen(pVal->devname)<=20))) ) {
		*pErrCode = ERR___po_hi_c_ip_conf_t_devname;
		return FALSE;
	}
	if ( !(((strlen(pVal->address)>=1) && (strlen(pVal->address)<=40))) ) {
		*pErrCode = ERR___po_hi_c_ip_conf_t_address;
		return FALSE;
	}
	if (pVal->exist.version) {
		if ( !__po_hi_c_Version_T_IsConstraintValid(&pVal->version, pErrCode)) 
			return FALSE;

	}
	if ( !__po_hi_c_Port_T_IsConstraintValid(&pVal->port, pErrCode)) 
		return FALSE;

	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_ip_conf_t_Equal(const __po_hi_c_ip_conf_t* pVal1, const __po_hi_c_ip_conf_t* pVal2) 
{
	if (strcmp(pVal1->devname, pVal2->devname) !=0)
		return FALSE;
	if (strcmp(pVal1->address, pVal2->address) !=0)
		return FALSE;
	if (pVal1->exist.version != pVal2->exist.version)
		return FALSE;
	if (pVal1->exist.version) {
		if (!__po_hi_c_Version_T_Equal(&pVal1->version, &pVal2->version))
			return FALSE;
	}
	if (!__po_hi_c_Port_T_Equal(&pVal1->port, &pVal2->port))
		return FALSE;
	return TRUE;
}







