/*
Code automatically generated by asn1scc tool
Date was: 1/24/2011
Time was: 20:29:06
*/
#include <string.h>
#include <math.h>
#include "serial.h"


#ifndef _MSC_VER
#endif

void __po_hi_c_Baudrate_T_Initialize(__po_hi_c_Baudrate_T* pVal)
{
	*pVal = __po_hi_c_b9600;
}


flag __po_hi_c_Baudrate_T_IsConstraintValid(const __po_hi_c_Baudrate_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Baudrate_T_Equal(const __po_hi_c_Baudrate_T* pVal1, const __po_hi_c_Baudrate_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_Parity_T_Initialize(__po_hi_c_Parity_T* pVal)
{
	*pVal = __po_hi_c_even;
}


flag __po_hi_c_Parity_T_IsConstraintValid(const __po_hi_c_Parity_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Parity_T_Equal(const __po_hi_c_Parity_T* pVal1, const __po_hi_c_Parity_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_serial_conf_t_Initialize(__po_hi_c_serial_conf_t* pVal)
{
	memset(pVal->devname, 0x0, 21);
	__po_hi_c_Baudrate_T_Initialize(&pVal->speed);
	__po_hi_c_Parity_T_Initialize(&pVal->parity);
	pVal->bits = 7;
	pVal->use_paritybit = FALSE;
}


flag __po_hi_c_serial_conf_t_IsConstraintValid(const __po_hi_c_serial_conf_t* pVal, int* pErrCode) 
{
	if ( !(((strlen(pVal->devname)>=1) && (strlen(pVal->devname)<=20))) ) {
		*pErrCode = ERR___po_hi_c_serial_conf_t_devname;
		return FALSE;
	}
	if (pVal->exist.speed) {
		if ( !__po_hi_c_Baudrate_T_IsConstraintValid(&pVal->speed, pErrCode)) 
			return FALSE;

	}
	if (pVal->exist.parity) {
		if ( !__po_hi_c_Parity_T_IsConstraintValid(&pVal->parity, pErrCode)) 
			return FALSE;

	}
	if (pVal->exist.bits) {
		if ( !(((pVal->bits>=7) && (pVal->bits<=8))) ) {
			*pErrCode = ERR___po_hi_c_serial_conf_t_bits;
			return FALSE;
		}
	}
	if (pVal->exist.use_paritybit) {
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_serial_conf_t_Equal(const __po_hi_c_serial_conf_t* pVal1, const __po_hi_c_serial_conf_t* pVal2) 
{
	if (strcmp(pVal1->devname, pVal2->devname) !=0)
		return FALSE;
	if (pVal1->exist.speed != pVal2->exist.speed)
		return FALSE;
	if (pVal1->exist.speed) {
		if (!__po_hi_c_Baudrate_T_Equal(&pVal1->speed, &pVal2->speed))
			return FALSE;
	}
	if (pVal1->exist.parity != pVal2->exist.parity)
		return FALSE;
	if (pVal1->exist.parity) {
		if (!__po_hi_c_Parity_T_Equal(&pVal1->parity, &pVal2->parity))
			return FALSE;
	}
	if (pVal1->exist.bits != pVal2->exist.bits)
		return FALSE;
	if (pVal1->exist.bits) {
		if (pVal1->bits != pVal2->bits) 
			return FALSE;
	}
	if (pVal1->exist.use_paritybit != pVal2->exist.use_paritybit)
		return FALSE;
	if (pVal1->exist.use_paritybit) {
		if ( (pVal1->use_paritybit && !pVal2->use_paritybit) || (!pVal1->use_paritybit && pVal2->use_paritybit))
			return FALSE;
	}
	return TRUE;
}







