#if (defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX) || defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX_RECEIVER) || defined (__PO_HI_NEED_DRIVER_SERIAL_LINUX_SENDER) || defined (__PO_HI_NEED_DRIVER_SERIAL_RASTA) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON_SENDER) || defined (__PO_HI_NEED_DRIVER_SERIAL_LEON_RECEIVER))\n
/*
Code automatically generated by asn1scc tool
Date was: 12/21/2011
Time was: 19:16:32
*/
#include <string.h>
#include <math.h>
#include "serial.h"


#ifndef _MSC_VER
__po_hi_c_serial_conf_t linux_ttyS0 = {
	.devname = "/dev/ttyS0",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
__po_hi_c_serial_conf_t linux_ttyUSB0 = {
	.devname = "/dev/ttyUSB0",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
__po_hi_c_serial_conf_t linux_ttyUSB1 = {
	.devname = "/dev/ttyUSB1",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
__po_hi_c_serial_conf_t linux_ttyUSB2 = {
	.devname = "/dev/ttyUSB2",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
__po_hi_c_serial_conf_t leon_rasta_apburasta0 = {
	.devname = "/dev/apburasta0",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
__po_hi_c_serial_conf_t leon_rasta_apburasta1 = {
	.devname = "/dev/apburasta1",
	.speed = __po_hi_c_b38400,
	.exist = {
		.speed = 1
	}
}; 
#endif

void __po_hi_c_Baudrate_T_Initialize(__po_hi_c_Baudrate_T* pVal)
{
	*pVal = __po_hi_c_b9600;
}


flag __po_hi_c_Baudrate_T_IsConstraintValid(const __po_hi_c_Baudrate_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}




void __po_hi_c_Parity_T_Initialize(__po_hi_c_Parity_T* pVal)
{
	*pVal = __po_hi_c_even;
}


flag __po_hi_c_Parity_T_IsConstraintValid(const __po_hi_c_Parity_T* pVal, int* pErrCode) 
{
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}




void __po_hi_c_serial_conf_t_Initialize(__po_hi_c_serial_conf_t* pVal)
{
	memset(pVal->devname, 0x0, 21);
	__po_hi_c_Baudrate_T_Initialize(&pVal->speed);
	__po_hi_c_Parity_T_Initialize(&pVal->parity);
	pVal->bits = 7;
	pVal->sending_wait = 0;
	pVal->use_paritybit = FALSE;
}


flag __po_hi_c_serial_conf_t_IsConstraintValid(const __po_hi_c_serial_conf_t* pVal, int* pErrCode) 
{
	if ( !(((strlen(pVal->devname)>=1) && (strlen(pVal->devname)<=20))) ) {
		*pErrCode = ERR___po_hi_c_serial_conf_t_devname;
		return FALSE;
	}
	if (pVal->exist.speed) {
		if ( !__po_hi_c_Baudrate_T_IsConstraintValid(&pVal->speed, pErrCode)) 
			return FALSE;

	}
	if (pVal->exist.parity) {
		if ( !__po_hi_c_Parity_T_IsConstraintValid(&pVal->parity, pErrCode)) 
			return FALSE;

	}
	if (pVal->exist.bits) {
		if ( !(((pVal->bits>=7) && (pVal->bits<=8))) ) {
			*pErrCode = ERR___po_hi_c_serial_conf_t_bits;
			return FALSE;
		}
	}
	if (pVal->exist.sending_wait) {
		if ( !(((pVal->sending_wait>=0) && (pVal->sending_wait<=9000000))) ) {
			*pErrCode = ERR___po_hi_c_serial_conf_t_sending_wait;
			return FALSE;
		}
	}
	if (pVal->exist.use_paritybit) {
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}





\n#endif
