/*
Code automatically generated by asn1scc tool
Date was: 1/24/2011
Time was: 20:29:08
*/
#include <string.h>
#include <math.h>
#include "spacewire.h"


#ifndef _MSC_VER
#endif

void __po_hi_c_Core_Frequence_T_Initialize(__po_hi_c_Core_Frequence_T* pVal)
{
	*pVal = 0;
}


flag __po_hi_c_Core_Frequence_T_IsConstraintValid(const __po_hi_c_Core_Frequence_T* pVal, int* pErrCode) 
{
	if ( !(((*pVal>=0) && (*pVal<=4294967295LL))) ) {
		*pErrCode = ERR___po_hi_c_Core_Frequence_T;
		return FALSE;
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Core_Frequence_T_Equal(const __po_hi_c_Core_Frequence_T* pVal1, const __po_hi_c_Core_Frequence_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_Node_Addr_T_Initialize(__po_hi_c_Node_Addr_T* pVal)
{
	*pVal = 0;
}


flag __po_hi_c_Node_Addr_T_IsConstraintValid(const __po_hi_c_Node_Addr_T* pVal, int* pErrCode) 
{
	if ( !(((*pVal>=0) && (*pVal<=255))) ) {
		*pErrCode = ERR___po_hi_c_Node_Addr_T;
		return FALSE;
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Node_Addr_T_Equal(const __po_hi_c_Node_Addr_T* pVal1, const __po_hi_c_Node_Addr_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_Clock_Division_T_Initialize(__po_hi_c_Clock_Division_T* pVal)
{
	*pVal = 0;
}


flag __po_hi_c_Clock_Division_T_IsConstraintValid(const __po_hi_c_Clock_Division_T* pVal, int* pErrCode) 
{
	if ( !(((*pVal>=0) && (*pVal<=255))) ) {
		*pErrCode = ERR___po_hi_c_Clock_Division_T;
		return FALSE;
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_Clock_Division_T_Equal(const __po_hi_c_Clock_Division_T* pVal1, const __po_hi_c_Clock_Division_T* pVal2) 
{
	if (*pVal1 != *pVal2) 
		return FALSE;
	return TRUE;
}






void __po_hi_c_spacewire_conf_t_Initialize(__po_hi_c_spacewire_conf_t* pVal)
{
	memset(pVal->devname, 0x0, 21);
	pVal->nodeaddr = 0;
	pVal->corefreq = 0;
	pVal->clockdiv = 0;
	pVal->remove_prot_id = FALSE;
	pVal->rxblock = FALSE;
	pVal->txblock = FALSE;
}


flag __po_hi_c_spacewire_conf_t_IsConstraintValid(const __po_hi_c_spacewire_conf_t* pVal, int* pErrCode) 
{
	if ( !(((strlen(pVal->devname)>=1) && (strlen(pVal->devname)<=20))) ) {
		*pErrCode = ERR___po_hi_c_spacewire_conf_t_devname;
		return FALSE;
	}
	if ( !__po_hi_c_Node_Addr_T_IsConstraintValid(&pVal->nodeaddr, pErrCode)) 
		return FALSE;

	if ( !__po_hi_c_Core_Frequence_T_IsConstraintValid(&pVal->corefreq, pErrCode)) 
		return FALSE;

	if ( !__po_hi_c_Clock_Division_T_IsConstraintValid(&pVal->clockdiv, pErrCode)) 
		return FALSE;

	if (pVal->exist.remove_prot_id) {
	}
	if (pVal->exist.rxblock) {
	}
	if (pVal->exist.txblock) {
	}
	(void)pVal; /*Dummy statement, just to hide potential warning*/
	(void)pErrCode; /*Dummy statement, just to hide potential warning*/
	return TRUE;
}

flag __po_hi_c_spacewire_conf_t_Equal(const __po_hi_c_spacewire_conf_t* pVal1, const __po_hi_c_spacewire_conf_t* pVal2) 
{
	if (strcmp(pVal1->devname, pVal2->devname) !=0)
		return FALSE;
	if (!__po_hi_c_Node_Addr_T_Equal(&pVal1->nodeaddr, &pVal2->nodeaddr))
		return FALSE;
	if (!__po_hi_c_Core_Frequence_T_Equal(&pVal1->corefreq, &pVal2->corefreq))
		return FALSE;
	if (!__po_hi_c_Clock_Division_T_Equal(&pVal1->clockdiv, &pVal2->clockdiv))
		return FALSE;
	if (pVal1->exist.remove_prot_id != pVal2->exist.remove_prot_id)
		return FALSE;
	if (pVal1->exist.remove_prot_id) {
		if ( (pVal1->remove_prot_id && !pVal2->remove_prot_id) || (!pVal1->remove_prot_id && pVal2->remove_prot_id))
			return FALSE;
	}
	if (pVal1->exist.rxblock != pVal2->exist.rxblock)
		return FALSE;
	if (pVal1->exist.rxblock) {
		if ( (pVal1->rxblock && !pVal2->rxblock) || (!pVal1->rxblock && pVal2->rxblock))
			return FALSE;
	}
	if (pVal1->exist.txblock != pVal2->exist.txblock)
		return FALSE;
	if (pVal1->exist.txblock) {
		if ( (pVal1->txblock && !pVal2->txblock) || (!pVal1->txblock && pVal2->txblock))
			return FALSE;
	}
	return TRUE;
}







