#if (defined (__PO_HI_NEED_DRIVER_SPACEWIRE_RASTA))\n
/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "spacewire.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Core_Frequence_T_Initialize(__po_hi_c_Core_Frequence_T* pVal)
{
    *pVal = (__po_hi_c_Core_Frequence_T) 0;
}
#endif

 
flag __po_hi_c_Core_Frequence_T_IsConstraintValid(const __po_hi_c_Core_Frequence_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= *pVal && *pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR___po_hi_c_Core_Frequence_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Node_Addr_T_Initialize(__po_hi_c_Node_Addr_T* pVal)
{
    *pVal = (__po_hi_c_Node_Addr_T) 0;
}
#endif

 
flag __po_hi_c_Node_Addr_T_IsConstraintValid(const __po_hi_c_Node_Addr_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= *pVal && *pVal <= 255);
	*pErrCode = ret ? 0 : ERR___po_hi_c_Node_Addr_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_Clock_Division_T_Initialize(__po_hi_c_Clock_Division_T* pVal)
{
    *pVal = (__po_hi_c_Clock_Division_T) 0;
}
#endif

 
flag __po_hi_c_Clock_Division_T_IsConstraintValid(const __po_hi_c_Clock_Division_T* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= *pVal && *pVal <= 255);
	*pErrCode = ret ? 0 : ERR___po_hi_c_Clock_Division_T;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_spacewire_conf_t_devname_Initialize(__po_hi_c_spacewire_conf_t_devname pVal)
{
    static __po_hi_c_spacewire_conf_t_devname ret = 
        " ";
    strcpy(pVal, ret);
}
#endif

 
flag __po_hi_c_spacewire_conf_t_devname_IsConstraintValid(const __po_hi_c_spacewire_conf_t_devname pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= strlen(pVal) && strlen(pVal) <= 20);
	*pErrCode = ret ? 0 : ERR___po_hi_c_spacewire_conf_t_devname;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void __po_hi_c_spacewire_conf_t_Initialize(__po_hi_c_spacewire_conf_t* pVal)
{
    *pVal = (__po_hi_c_spacewire_conf_t) {
    .devname = " ",
    .nodeaddr = 0,
    .corefreq = 0,
    .clockdiv = 0,
    .use_router = FALSE,
    .remove_prot_id = FALSE,
    .rxblock = FALSE,
    .txblock = FALSE,
    .exist = {
        .corefreq = 1,
        .clockdiv = 1,
        .use_router = 1,
        .remove_prot_id = 1,
        .rxblock = 1,
        .txblock = 1
    }
};
}
#endif

 
flag __po_hi_c_spacewire_conf_t_IsConstraintValid(const __po_hi_c_spacewire_conf_t* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = __po_hi_c_spacewire_conf_t_devname_IsConstraintValid(pVal->devname, pErrCode);
	if (ret) {
	    ret = __po_hi_c_Node_Addr_T_IsConstraintValid(&pVal->nodeaddr, pErrCode);
	    if (ret) {
	        if (pVal->exist.corefreq==1) {
	            ret = __po_hi_c_Core_Frequence_T_IsConstraintValid(&pVal->corefreq, pErrCode);
	        }
	        if (ret) {
	            if (pVal->exist.clockdiv==1) {
	                ret = __po_hi_c_Clock_Division_T_IsConstraintValid(&pVal->clockdiv, pErrCode);
	            }
	            if (ret) {
	                if (pVal->exist.use_router==1) {
	                    ret = TRUE; *pErrCode = 0;
	                }
	                if (ret) {
	                    if (pVal->exist.remove_prot_id==1) {
	                        ret = TRUE; *pErrCode = 0;
	                    }
	                    if (ret) {
	                        if (pVal->exist.rxblock==1) {
	                            ret = TRUE; *pErrCode = 0;
	                        }
	                        if (ret) {
	                            if (pVal->exist.txblock==1) {
	                                ret = TRUE; *pErrCode = 0;
	                            }
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

const __po_hi_c_spacewire_conf_t leon_rasta_spw_sender = {
    .devname = "/dev/grspwrasta0",
    .nodeaddr = 11,
    .corefreq = 0,
    .clockdiv = 0,
    .use_router = FALSE,
    .remove_prot_id = FALSE,
    .rxblock = FALSE,
    .txblock = FALSE,
    .exist = {
        .corefreq = 0,
        .clockdiv = 0,
        .use_router = 0,
        .remove_prot_id = 0,
        .rxblock = 0,
        .txblock = 0
    }
};

const __po_hi_c_spacewire_conf_t leon_rasta_spw_receiver = {
    .devname = "/dev/grspwrasta0",
    .nodeaddr = 22,
    .corefreq = 0,
    .clockdiv = 0,
    .use_router = FALSE,
    .remove_prot_id = FALSE,
    .rxblock = FALSE,
    .txblock = FALSE,
    .exist = {
        .corefreq = 0,
        .clockdiv = 0,
        .use_router = 0,
        .remove_prot_id = 0,
        .rxblock = 0,
        .txblock = 0
    }
};
\n#endif
